/* ======================================
   INDIA LOCATIONS DATA - COMPREHENSIVE
   ====================================== */

const locationsData = {
  // All Indian States and Union Territories with Major Cities
  states: {
    "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Tirupati"],
    "Arunachal Pradesh": ["Itanagar", "Naharlagun", "Pasighat", "Tawang"],
    "Assam": ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon"],
    "Bihar": ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Darbhanga"],
    "Chhattisgarh": ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg"],
    "Goa": ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda"],
    "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Gandhinagar"],
    "Haryana": ["Gurugram", "Faridabad", "Panipat", "Ambala", "Karnal", "Rohtak"],
    "Himachal Pradesh": ["Shimla", "Manali", "Dharamshala", "Kullu", "Solan"],
    "Jharkhand": ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Hazaribagh"],
    "Karnataka": ["Bangalore", "Mysore", "Mangalore", "Hubli", "Belgaum"],
    "Kerala": ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam"],
    "Madhya Pradesh": ["Bhopal", "Indore", "Gwalior", "Jabalpur", "Ujjain"],
    "Maharashtra": ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad", "Thane"],
    "Manipur": ["Imphal", "Thoubal", "Churachandpur"],
    "Meghalaya": ["Shillong", "Tura", "Jowai"],
    "Mizoram": ["Aizawl", "Lunglei", "Champhai"],
    "Nagaland": ["Kohima", "Dimapur", "Mokokchung"],
    "Odisha": ["Bhubaneswar", "Cuttack", "Puri", "Rourkela", "Berhampur"],
    "Punjab": ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda"],
    "Rajasthan": ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Ajmer", "Bikaner"],
    "Sikkim": ["Gangtok", "Namchi", "Gyalshing", "Mangan"],
    "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Salem", "Tiruchirappalli"],
    "Telangana": ["Hyderabad", "Warangal", "Nizamabad", "Khammam", "Karimnagar"],
    "Tripura": ["Agartala", "Udaipur", "Dharmanagar"],
    "Uttar Pradesh": ["Lucknow", "Kanpur", "Agra", "Varanasi", "Prayagraj", "Noida"],
    "Uttarakhand": ["Dehradun", "Haridwar", "Rishikesh", "Nainital", "Mussoorie"],
    "West Bengal": ["Kolkata", "Howrah", "Durgapur", "Siliguri", "Asansol"],
    "Delhi": ["New Delhi", "Connaught Place", "Chandni Chowk", "Karol Bagh", "Dwarka"],
    "Jammu and Kashmir": ["Srinagar", "Jammu", "Anantnag", "Baramulla"],
    "Ladakh": ["Leh", "Kargil", "Nubra Valley"],
    "Puducherry": ["Puducherry City", "Karaikal", "Mahe", "Yanam"],
    "Chandigarh": ["Sector 17", "Sector 22", "Panchkula"],
    "Dadra and Nagar Haveli and Daman and Diu": ["Daman", "Diu", "Silvassa"],
    "Lakshadweep": ["Kavaratti", "Agatti", "Minicoy"],
    "Andaman and Nicobar Islands": ["Port Blair", "Diglipur", "Car Nicobar"]
  },

  // Comprehensive Rajasthan District Data
  rajasthan: {
    "Jaipur": {
      forts: ["Amer Fort", "Nahargarh Fort", "Jaigarh Fort", "Moti Dungri Fort"],
      temples: ["Birla Mandir", "Govind Dev Ji Temple", "Galtaji Temple", "Garh Ganesh Temple"],
      tourist_places: ["Hawa Mahal", "City Palace", "Jantar Mantar", "Jal Mahal", "Albert Hall Museum"],
      hospitals: ["SMS Hospital", "Fortis Escorts Hospital", "Manipal Hospital", "Narayana Multispecialty Hospital"],
      railway_stations: ["Jaipur Junction", "Durgapura Railway Station", "Gandhinagar Jaipur"],
      airports: ["Jaipur International Airport"],
      bus_stands: ["Sindhi Camp Bus Stand", "Narayan Singh Circle"],
      markets: ["Johari Bazaar", "Bapu Bazaar", "Tripolia Bazaar", "MI Road"],
      landmarks: ["Rambagh Palace", "Jawahar Circle", "World Trade Park"]
    },
    "Jodhpur": {
      forts: ["Mehrangarh Fort", "Umaid Bhawan Palace"],
      temples: ["Chamunda Mataji Temple", "Rao Jodha Desert Rock Park"],
      tourist_places: ["Clock Tower", "Mandore Gardens", "Jaswant Thada", "Blue City Streets"],
      hospitals: ["Mathura Das Mathur Hospital", "Goyal Hospital"],
      railway_stations: ["Jodhpur Junction"],
      airports: ["Jodhpur Airport"],
      bus_stands: ["Main Bus Stand Jodhpur"],
      markets: ["Sardar Market", "Clock Tower Market", "Sojati Gate"],
      landmarks: ["Kaylana Lake", "Balsamand Lake"]
    },
    "Udaipur": {
      forts: ["City Palace Udaipur", "Monsoon Palace", "Kumbhalgarh Fort"],
      temples: ["Jagdish Temple", "Eklingji Temple", "Karni Mata Temple"],
      tourist_places: ["Lake Pichola", "Fateh Sagar Lake", "Saheliyon Ki Bari", "Bagore Ki Haveli"],
      hospitals: ["Geetanjali Medical College", "Paras JK Hospital"],
      railway_stations: ["Udaipur City Railway Station"],
      airports: ["Maharana Pratap Airport"],
      bus_stands: ["Udaipur Bus Stand"],
      markets: ["Hathi Pol Bazaar", "Bada Bazaar", "Shilpgram"],
      landmarks: ["Lake Palace", "Jag Mandir", "Sajjangarh"]
    },
    "Ajmer": {
      forts: ["Taragarh Fort"],
      temples: ["Brahma Temple Pushkar", "Savitri Temple", "Nareli Jain Temple"],
      tourist_places: ["Ajmer Sharif Dargah", "Ana Sagar Lake", "Pushkar Lake", "Pushkar Camel Fair Ground"],
      hospitals: ["JLN Hospital", "Ajmer Hospital"],
      railway_stations: ["Ajmer Junction"],
      airports: ["Kishangarh Airport"],
      bus_stands: ["Ajmer Bus Stand"],
      markets: ["Naya Bazaar", "Purani Mandi", "Pushkar Market"],
      landmarks: ["Adhai Din Ka Jhonpra", "Mayo College"]
    },
    "Kota": {
      forts: ["Garh Palace", "Kota Fort"],
      temples: ["Mathuradheesh Temple", "Kishore Sagar Temple"],
      tourist_places: ["Seven Wonders Park", "Chambal Garden", "Kishore Sagar Lake"],
      hospitals: ["MBS Hospital", "Maharao Bhim Singh Hospital"],
      railway_stations: ["Kota Junction"],
      airports: [],
      bus_stands: ["Kota Bus Stand"],
      markets: ["Rampura Circle", "Dadabari Market"],
      landmarks: ["Chambal River", "Jag Mandir Palace"]
    },
    "Bikaner": {
      forts: ["Junagarh Fort", "Laxmi Niwas Palace"],
      temples: ["Karni Mata Temple (Rat Temple)", "Bhandasar Jain Temple"],
      tourist_places: ["National Research Centre on Camel", "Gajner Palace", "Rampuria Haveli"],
      hospitals: ["PBM Hospital"],
      railway_stations: ["Bikaner Junction"],
      airports: ["Nal Airport"],
      bus_stands: ["Bikaner Bus Stand"],
      markets: ["Kote Gate Market", "Station Road Market"],
      landmarks: ["Lalgarh Palace", "Ganga Golden Jubilee Museum"]
    },
    "Jaisalmer": {
      forts: ["Jaisalmer Fort (Sonar Quila)", "Golden Fort"],
      temples: ["Tanot Mata Temple", "Jain Temples Jaisalmer"],
      tourist_places: ["Sam Sand Dunes", "Patwon Ki Haveli", "Gadisar Lake", "Desert National Park"],
      hospitals: ["MG Hospital Jaisalmer"],
      railway_stations: ["Jaisalmer Railway Station"],
      airports: ["Jaisalmer Airport"],
      bus_stands: ["Jaisalmer Bus Stand"],
      markets: ["Sadar Bazaar", "Manak Chowk"],
      landmarks: ["Bada Bagh", "Nathmal Ki Haveli"]
    },
    "Alwar": {
      forts: ["Bala Quila", "Alwar Fort"],
      temples: ["Neelkanth Temples", "Pandupol Temple"],
      tourist_places: ["Siliserh Lake", "Sariska Tiger Reserve", "City Palace Alwar"],
      hospitals: ["General Hospital Alwar"],
      railway_stations: ["Alwar Junction"],
      airports: [],
      bus_stands: ["Alwar Bus Stand"],
      markets: ["Hope Circus Market"],
      landmarks: ["Vijay Mandir Palace", "Moosi Maharani ki Chhatri"]
    },
    "Bharatpur": {
      forts: ["Lohagarh Fort"],
      temples: ["Ganga Mandir", "Laxman Mandir"],
      tourist_places: ["Keoladeo National Park", "Deeg Palace", "Bharatpur Palace"],
      hospitals: ["Government Hospital Bharatpur"],
      railway_stations: ["Bharatpur Junction"],
      airports: [],
      bus_stands: ["Bharatpur Bus Stand"],
      markets: ["Gopalgarh Market"],
      landmarks: ["Bharatpur Museum", "Bandh Baretha"]
    },
    "Bhilwara": {
      forts: ["Mandalgarh Fort"],
      temples: ["Harni Mahadev Temple", "Bijoliyan Temple"],
      tourist_places: ["Menal Waterfalls", "Badnore Fort"],
      hospitals: ["Bhilwara Hospital", "R N T Medical College"],
      railway_stations: ["Bhilwara Railway Station"],
      airports: [],
      bus_stands: ["Bhilwara Bus Stand"],
      markets: ["Pur Road Market", "City Center"],
      landmarks: ["Textile City Market"]
    },
    "Chittorgarh": {
      forts: ["Chittorgarh Fort", "Rana Kumbha Palace"],
      temples: ["Kalika Mata Temple", "Meera Temple", "Tulja Bhavani Temple"],
      tourist_places: ["Vijay Stambh", "Kirti Stambh", "Padmini Palace", "Rana Kumbha Palace"],
      hospitals: ["MB Hospital Chittorgarh"],
      railway_stations: ["Chittorgarh Junction"],
      airports: [],
      bus_stands: ["Chittorgarh Bus Stand"],
      markets: ["Fort Road Market"],
      landmarks: ["Gaumukh Reservoir", "Tower of Victory"]
    },
    "Churu": {
      forts: [],
      temples: ["Salasar Balaji Temple", "Rani Sati Temple"],
      tourist_places: ["Tal Chhapar Sanctuary", "Malji Ka Kamra"],
      hospitals: ["Government Hospital Churu"],
      railway_stations: ["Churu Junction"],
      airports: [],
      bus_stands: ["Churu Bus Stand"],
      markets: ["Main Market Churu"],
      landmarks: ["Grand Havelis"]
    },
    "Dausa": {
      forts: ["Dausa Fort", "Bhandarej Fort"],
      temples: ["Mehandipur Balaji Temple", "Nilkanth Mahadev"],
      tourist_places: ["Chand Baori (Abhaneri)", "Bhandarej"],
      hospitals: ["Government Hospital Dausa"],
      railway_stations: ["Bandikui Junction"],
      airports: [],
      bus_stands: ["Dausa Bus Stand"],
      markets: ["Main Market Dausa"],
      landmarks: ["Harshat Mata Temple"]
    },
    "Dholpur": {
      forts: ["Dholpur Fort", "Bari Palace"],
      temples: ["Machkund Temple", "Talab Shahi"],
      tourist_places: ["National Chambal Sanctuary", "Van Vihar"],
      hospitals: ["Government Hospital Dholpur"],
      railway_stations: ["Dholpur Railway Station"],
      airports: [],
      bus_stands: ["Dholpur Bus Stand"],
      markets: ["City Market Dholpur"],
      landmarks: ["Nihal Tower"]
    },
    "Dungarpur": {
      forts: ["Dungarpur Palace", "Juna Mahal"],
      temples: ["Baneshwar Temple", "Dev Somnath Temple"],
      tourist_places: ["Gaib Sagar Lake", "Badal Mahal"],
      hospitals: ["Government Hospital Dungarpur"],
      railway_stations: ["Dungarpur Railway Station"],
      airports: [],
      bus_stands: ["Dungarpur Bus Stand"],
      markets: ["Main Market"],
      landmarks: ["Udai Bilas Palace"]
    },
    "Hanumangarh": {
      forts: ["Bhatner Fort", "Kalibangan"],
      temples: ["Gogamedi Temple", "Bhadrakali Temple"],
      tourist_places: ["Ancient Kalibangan Site", "Brahmani Mata Temple"],
      hospitals: ["PBM Hospital Hanumangarh"],
      railway_stations: ["Hanumangarh Junction"],
      airports: [],
      bus_stands: ["Hanumangarh Bus Stand"],
      markets: ["Main Market Hanumangarh"],
      landmarks: ["Indira Gandhi Canal"]
    },
    "Jalore": {
      forts: ["Jalore Fort", "Sire Mandir"],
      temples: ["Sundha Mata Temple", "Malik Shah Peer"],
      tourist_places: ["Topoban", "Jalore Fort"],
      hospitals: ["Government Hospital Jalore"],
      railway_stations: ["Jalore Railway Station"],
      airports: [],
      bus_stands: ["Jalore Bus Stand"],
      markets: ["Main Market"],
      landmarks: ["Sire Mandir Fort"]
    },
    "Jhalawar": {
      forts: ["Gagron Fort", "Jhalawar Fort"],
      temples: ["Chandrabhaga Temple", "Sun Temple Jhalarapatan"],
      tourist_places: ["Bhimsagar Dam", "Jhalawar Fort Museum"],
      hospitals: ["Government Hospital Jhalawar"],
      railway_stations: ["Jhalawar Road"],
      airports: [],
      bus_stands: ["Jhalawar Bus Stand"],
      markets: ["Main Market Jhalawar"],
      landmarks: ["Rajasthan Government Opium Factory"]
    },
    "Jhunjhunu": {
      forts: ["Khetri Mahal", "Mandawa Fort"],
      temples: ["Rani Sati Temple", "Khemi Sati Temple"],
      tourist_places: ["Mandawa Havelis", "Nawalgarh", "Mukundgarh Fort"],
      hospitals: ["Nehru Hospital Jhunjhunu"],
      railway_stations: ["Jhunjhunu Railway Station"],
      airports: [],
      bus_stands: ["Jhunjhunu Bus Stand"],
      markets: ["Nehru Bazaar"],
      landmarks: ["Modi Haveli", "Kaniram Narsinghdas Tiberwala Haveli"]
    },
    "Karauli": {
      forts: ["Karauli Fort", "City Palace"],
      temples: ["Kaila Devi Temple", "Madan Mohan Ji Temple"],
      tourist_places: ["Kaila Devi Wildlife Sanctuary", "Timangarh Fort"],
      hospitals: ["Government Hospital Karauli"],
      railway_stations: ["Hindaun City"],
      airports: [],
      bus_stands: ["Karauli Bus Stand"],
      markets: ["Main Market Karauli"],
      landmarks: ["Shri Madan Mohanji Museum"]
    },
    "Nagaur": {
      forts: ["Nagaur Fort", "Ahhichatragarh Fort"],
      temples: ["Jain Glass Temple", "Tarkeen Dargah"],
      tourist_places: ["Nagaur Cattle Fair Ground", "Cenotaphs of Amar Singh"],
      hospitals: ["Mahatma Gandhi Hospital"],
      railway_stations: ["Nagaur Railway Station"],
      airports: [],
      bus_stands: ["Nagaur Bus Stand"],
      markets: ["Naya Bazaar"],
      landmarks: ["Saiji Ka Tanka", "Khinwsar"]
    },
    "Pali": {
      forts: ["Ranakpur Jain Temple", "Bangur Museum"],
      temples: ["Ranakpur Jain Temple", "Om Banna Temple", "Parshuram Mahadev Temple"],
      tourist_places: ["Jawai Bandh", "Nimaj", "Bullet Baba Temple"],
      hospitals: ["District Hospital Pali"],
      railway_stations: ["Pali Marwar"],
      airports: [],
      bus_stands: ["Pali Bus Stand"],
      markets: ["Station Road Market"],
      landmarks: ["Jain Temple Complex"]
    },
    "Pratapgarh": {
      forts: ["Pratapgarh Fort", "Devgarh Palace"],
      temples: ["Sitamata Wildlife Sanctuary Temple"],
      tourist_places: ["Devgarh Heritage", "Sitamata Sanctuary"],
      hospitals: ["Government Hospital Pratapgarh"],
      railway_stations: [],
      airports: [],
      bus_stands: ["Pratapgarh Bus Stand"],
      markets: ["Main Market"],
      landmarks: ["Devgarh Palace"]
    },
    "Rajsamand": {
      forts: ["Kumbhalgarh Fort", "Haldighati"],
      temples: ["Eklingji Temple", "Dwarkadheesh Temple"],
      tourist_places: ["Rajsamand Lake", "Nathdwara", "Kankroli"],
      hospitals: ["Government Hospital Rajsamand"],
      railway_stations: ["Rajsamand Railway Station"],
      airports: [],
      bus_stands: ["Rajsamand Bus Stand"],
      markets: ["Nathdwara Market", "Kankroli Market"],
      landmarks: ["Shrinathji Temple"]
    },
    "Sawai Madhopur": {
      forts: ["Ranthambore Fort"],
      temples: ["Trinetra Ganesh Temple"],
      tourist_places: ["Ranthambore National Park", "Ranthambore Fort", "Khandar Fort"],
      hospitals: ["Government Hospital Sawai Madhopur"],
      railway_stations: ["Sawai Madhopur Junction"],
      airports: [],
      bus_stands: ["Sawai Madhopur Bus Stand"],
      markets: ["Main Market Sawai Madhopur"],
      landmarks: ["Padam Talao", "Rajbagh Talao"]
    },
    "Sikar": {
      forts: ["Sikar Fort", "Laxmangarh Fort"],
      temples: ["Khatu Shyam Ji Temple", "Harsh Nath Temple"],
      tourist_places: ["Jeen Mata Temple", "Fatehpur Shekhawati Havelis"],
      hospitals: ["ESIC Hospital Sikar"],
      railway_stations: ["Sikar Railway Station"],
      airports: [],
      bus_stands: ["Sikar Bus Stand"],
      markets: ["Main Market Sikar"],
      landmarks: ["Devgarh Fort"]
    },
    "Sirohi": {
      forts: ["Sirohi Fort"],
      temples: ["Mount Abu Dilwara Temples", "Nakki Lake Temple"],
      tourist_places: ["Mount Abu", "Guru Shikhar", "Nakki Lake", "Achalgarh Fort"],
      hospitals: ["Government Hospital Sirohi"],
      railway_stations: ["Abu Road"],
      airports: [],
      bus_stands: ["Mount Abu Bus Stand", "Sirohi Bus Stand"],
      markets: ["Mount Abu Market", "Nakki Lake Market"],
      landmarks: ["Sunset Point", "Honeymoon Point"]
    },
    "Sri Ganganagar": {
      forts: ["Anupgarh Fort"],
      temples: ["Laila Majnu Tomb", "Hindumalkot Border"],
      tourist_places: ["Suratgarh Super Thermal Power Station"],
      hospitals: ["PBM Hospital Sri Ganganagar"],
      railway_stations: ["Sri Ganganagar Junction"],
      airports: [],
      bus_stands: ["Sri Ganganagar Bus Stand"],
      markets: ["Main Market"],
      landmarks: ["Canal Colony"]
    },
    "Tonk": {
      forts: ["Sunehri Kothi"],
      temples: ["Digamber Jain Temple"],
      tourist_places: ["Bisalpur Dam", "Arabic and Persian Research Institute"],
      hospitals: ["Government Hospital Tonk"],
      railway_stations: ["Tonk Railway Station"],
      airports: [],
      bus_stands: ["Tonk Bus Stand"],
      markets: ["Main Market Tonk"],
      landmarks: ["Jama Masjid"]
    },
    "Banswara": {
      forts: ["Banswara Fort"],
      temples: ["Tripura Sundari Temple", "Arthuna Temples"],
      tourist_places: ["Mahi Dam", "Kagdi Pick Up Weir", "Anand Sagar"],
      hospitals: ["Government Hospital Banswara"],
      railway_stations: [],
      airports: [],
      bus_stands: ["Banswara Bus Stand"],
      markets: ["Main Market"],
      landmarks: ["City of Hundred Islands"]
    },
    "Baran": {
      forts: ["Shergarh Fort"],
      temples: ["Bhand Devra Temple", "Ramgarh Vishdhari Sanctuary"],
      tourist_places: ["Sitabari Temple", "Bhimlat Waterfalls"],
      hospitals: ["Government Hospital Baran"],
      railway_stations: ["Baran Railway Station"],
      airports: [],
      bus_stands: ["Baran Bus Stand"],
      markets: ["Main Market Baran"],
      landmarks: ["Shahabad Fort"]
    },
    "Barmer": {
      forts: ["Barmer Fort", "Kiradu Temples"],
      temples: ["Kiradu Temples", "Nakoda Jain Temple"],
      tourist_places: ["Juna Fort", "Gadsisar Sagar"],
      hospitals: ["MG Hospital Barmer"],
      railway_stations: ["Barmer Railway Station"],
      airports: ["Uttarlai Airport"],
      bus_stands: ["Barmer Bus Stand"],
      markets: ["Main Market Barmer"],
      landmarks: ["Mallinath Temple"]
    },
    "Bundi": {
      forts: ["Taragarh Fort Bundi", "Bundi Palace"],
      temples: ["Raniji Ki Baori", "84 Pillared Cenotaph"],
      tourist_places: ["Taragarh Fort", "Nawal Sagar Lake", "Sukh Mahal"],
      hospitals: ["Government Hospital Bundi"],
      railway_stations: ["Bundi Railway Station"],
      airports: [],
      bus_stands: ["Bundi Bus Stand"],
      markets: ["Sadar Bazaar"],
      landmarks: ["Step Wells of Bundi"]
    },
    "Deeg": {
      forts: ["Deeg Fort"],
      temples: ["Jama Masjid Deeg"],
      tourist_places: ["Deeg Palace", "Gopal Bhawan"],
      hospitals: ["Community Health Centre Deeg"],
      railway_stations: [],
      airports: [],
      bus_stands: ["Deeg Bus Stand"],
      markets: ["Main Market"],
      landmarks: ["Water Palace"]
    },
    "Balotra": {
      forts: [],
      temples: ["Nakoda Parshwanath Temple"],
      tourist_places: ["Tilwara", "Mallinath Cattle Fair Ground"],
      hospitals: ["Government Hospital Balotra"],
      railway_stations: ["Balotra Railway Station"],
      airports: [],
      bus_stands: ["Balotra Bus Stand"],
      markets: ["Textile Market"],
      landmarks: ["Mallinath Pashu Mela"]
    },
    "Beawar": {
      forts: [],
      temples: ["Badshahbag", "Jagatpita Brahma Temple Area"],
      tourist_places: ["Archaeological Museum"],
      hospitals: ["Beawar Hospital"],
      railway_stations: ["Beawar Railway Station"],
      airports: [],
      bus_stands: ["Beawar Bus Stand"],
      markets: ["Masuria Market"],
      landmarks: ["Kharchi Hanuman Temple"]
    },
    "Didwana-Kuchaman": {
      forts: ["Kuchaman Fort"],
      temples: ["Meera Bai Temple Kuchaman"],
      tourist_places: ["Kuchaman City", "Salt Lake Didwana"],
      hospitals: ["Government Hospital Didwana"],
      railway_stations: ["Kuchaman City Railway Station"],
      airports: [],
      bus_stands: ["Didwana Bus Stand", "Kuchaman Bus Stand"],
      markets: ["Kuchaman Market"],
      landmarks: ["Kuchaman Fort Palace"]
    },
    "Gangapur City": {
      forts: [],
      temples: ["Brij Raj Bhawan Temple"],
      tourist_places: ["Bhimsagar Lake"],
      hospitals: ["Government Hospital Gangapur"],
      railway_stations: ["Gangapur City Railway Station"],
      airports: [],
      bus_stands: ["Gangapur City Bus Stand"],
      markets: ["Main Market"],
      landmarks: ["Industrial Area"]
    },
    "Jaipur Rural": {
      forts: ["Amber Fort Area"],
      temples: ["Shila Devi Temple"],
      tourist_places: ["Rural Heritage Sites"],
      hospitals: ["PHC Centers"],
      railway_stations: [],
      airports: [],
      bus_stands: ["Various Village Bus Stops"],
      markets: ["Local Haats"],
      landmarks: ["Rural Tourism Sites"]
    },
    "Jodhpur Rural": {
      forts: [],
      temples: ["Village Temples"],
      tourist_places: ["Bishnoi Villages", "Rural Tourism"],
      hospitals: ["PHC Centers"],
      railway_stations: [],
      airports: [],
      bus_stands: ["Village Bus Stops"],
      markets: ["Village Markets"],
      landmarks: ["Traditional Villages"]
    },
    "Kekri": {
      forts: [],
      temples: ["Local Temples"],
      tourist_places: ["Kekri Town"],
      hospitals: ["Government Hospital Kekri"],
      railway_stations: [],
      airports: [],
      bus_stands: ["Kekri Bus Stand"],
      markets: ["Main Market"],
      landmarks: ["Historical Sites"]
    },
    "Khairthal-Tijara": {
      forts: ["Tijara Fort"],
      temples: ["Balaji Temple"],
      tourist_places: ["Tijara Heritage"],
      hospitals: ["Community Health Centre"],
      railway_stations: [],
      airports: [],
      bus_stands: ["Tijara Bus Stand"],
      markets: ["Tijara Market"],
      landmarks: ["Fort Palace"]
    },
    "Kotputli-Behror": {
      forts: [],
      temples: ["Local Temples"],
      tourist_places: ["Behror Industrial Area"],
      hospitals: ["Government Hospital Kotputli"],
      railway_stations: ["Behror Railway Station"],
      airports: [],
      bus_stands: ["Kotputli Bus Stand", "Behror Bus Stand"],
      markets: ["Main Markets"],
      landmarks: ["Industrial Hubs"]
    },
    "Neem Ka Thana": {
      forts: [],
      temples: ["Khatu Shyam Temple Nearby"],
      tourist_places: ["Neem Ka Thana Town"],
      hospitals: ["Government Hospital"],
      railway_stations: ["Neem Ka Thana Railway Station"],
      airports: [],
      bus_stands: ["Main Bus Stand"],
      markets: ["Local Market"],
      landmarks: ["Historical Town"]
    },
    "Phalodi": {
      forts: [],
      temples: ["Ramdevra Temple", "Laxmi Nath Temple"],
      tourist_places: ["Salt Industry", "Desert Areas"],
      hospitals: ["Government Hospital Phalodi"],
      railway_stations: ["Phalodi Railway Station"],
      airports: [],
      bus_stands: ["Phalodi Bus Stand"],
      markets: ["Main Market"],
      landmarks: ["Salt Trading Centre"]
    },
    "Salumbar": {
      forts: [],
      temples: ["Tribal Temples"],
      tourist_places: ["Tribal Heritage Area"],
      hospitals: ["Community Health Centre"],
      railway_stations: [],
      airports: [],
      bus_stands: ["Salumbar Bus Stand"],
      markets: ["Tribal Market"],
      landmarks: ["Tribal Cultural Sites"]
    },
    "Sanchore": {
      forts: [],
      temples: ["Jain Temples"],
      tourist_places: ["Sanchore Town"],
      hospitals: ["Government Hospital"],
      railway_stations: ["Sanchore Railway Station"],
      airports: [],
      bus_stands: ["Sanchore Bus Stand"],
      markets: ["Main Market"],
      landmarks: ["Commercial Centre"]
    },
    "Shahpura": {
      forts: ["Shahpura Fort Palace"],
      temples: ["Phool Mahal Palace Temple"],
      tourist_places: ["Shahpura Heritage Hotels"],
      hospitals: ["Government Hospital Shahpura"],
      railway_stations: ["Shahpura Railway Station"],
      airports: [],
      bus_stands: ["Shahpura Bus Stand"],
      markets: ["Local Market"],
      landmarks: ["Heritage Hotels"]
    }
  }
};

// Export flat location array for backward compatibility
window.LOCATIONS = [];
window.locationsData = locationsData;
