const dotenv = require('dotenv');

dotenv.config();

const requiredEnv = ['MONGO_URI', 'JWT_SECRET', 'FIREBASE_KEY'];
requiredEnv.forEach((name) => {
  if (!process.env[name]) {
    if (process.env.NODE_ENV !== 'test') {
      throw new Error(`Missing required environment variable: ${name}`);
    }
  }
});

function splitCsv(value) {
  return String(value || '')
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean);
}

module.exports = {
  port: Number(process.env.PORT || 5000),
  mongoUri: process.env.MONGO_URI,
  jwtSecret: process.env.JWT_SECRET,
  jwtRefreshSecret: process.env.JWT_REFRESH_SECRET || process.env.JWT_SECRET,
  jwtIssuer: process.env.JWT_ISSUER || '',
  jwtAudience: process.env.JWT_AUDIENCE || '',
  jwtAccessScopesCustomer: splitCsv(process.env.JWT_ACCESS_SCOPES_CUSTOMER || 'wallet.write,booking.write,profile.write,notification.read'),
  jwtAccessScopesDriver: splitCsv(process.env.JWT_ACCESS_SCOPES_DRIVER || 'wallet.write,booking.write,profile.write,notification.read'),
  jwtAccessScopesAdmin: splitCsv(process.env.JWT_ACCESS_SCOPES_ADMIN || 'admin.full,admin.write,security.write,wallet.write,booking.write,user.write,notification.read'),
  firebaseKey: process.env.FIREBASE_KEY,
  recaptchaSecret: process.env.RECAPTCHA_SECRET,
  apiSignatureSecret: process.env.API_SIGNATURE_SECRET || process.env.JWT_SECRET,
  corsOrigin: process.env.CORS_ORIGIN || 'https://goindiaride.in',
  accessTokenTtl: process.env.ACCESS_TOKEN_TTL || '15m',
  refreshTokenTtl: process.env.REFRESH_TOKEN_TTL || '30d',
  adminAllowedIps: splitCsv(process.env.ADMIN_ALLOWED_IPS),
  admin2FASecret: process.env.ADMIN_2FA_SECRET,

  strictSecurityMode: String(process.env.STRICT_SECURITY_MODE || 'true').toLowerCase() === 'true',
  maxJsonBodyKb: Number(process.env.MAX_JSON_BODY_KB || 128),
  requestAutoBlockScore: Number(process.env.REQUEST_AUTO_BLOCK_SCORE || 85),
  requestIncidentScore: Number(process.env.REQUEST_INCIDENT_SCORE || 55),
  securityAllowedOrigins: splitCsv(process.env.SECURITY_ALLOWED_ORIGINS),
  securityControlPlaneShieldEnabled: String(process.env.SECURITY_CONTROL_PLANE_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  securityControlPlaneStrictSignature: String(process.env.SECURITY_CONTROL_PLANE_STRICT_SIGNATURE || 'true').toLowerCase() === 'true',
  securityControlPlaneEnforceAdminIp: String(process.env.SECURITY_CONTROL_PLANE_ENFORCE_ADMIN_IP || 'true').toLowerCase() === 'true',
  securityControlPlaneCriticalRateLimitEnabled: String(process.env.SECURITY_CONTROL_PLANE_CRITICAL_RATE_LIMIT_ENABLED || 'true').toLowerCase() === 'true',
  securityControlPlaneFailOpen: String(process.env.SECURITY_CONTROL_PLANE_FAIL_OPEN || 'false').toLowerCase() === 'true',
  securityControlPlaneProtectedPrefixes: splitCsv(process.env.SECURITY_CONTROL_PLANE_PROTECTED_PREFIXES || '/api/security/incidents,/api/security/shield,/api/security/runtime/security,/api/security/policy'),
  idempotencyShieldEnabled: String(process.env.IDEMPOTENCY_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  idempotencyShieldRequireHeader: String(process.env.IDEMPOTENCY_SHIELD_REQUIRE_HEADER || 'true').toLowerCase() === 'true',
  idempotencyShieldStrictPayloadMatch: String(process.env.IDEMPOTENCY_SHIELD_STRICT_PAYLOAD_MATCH || 'true').toLowerCase() === 'true',
  idempotencyShieldFailOpen: String(process.env.IDEMPOTENCY_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  idempotencyShieldMinKeyLength: Number(process.env.IDEMPOTENCY_SHIELD_MIN_KEY_LENGTH || 16),
  idempotencyShieldMaxKeyLength: Number(process.env.IDEMPOTENCY_SHIELD_MAX_KEY_LENGTH || 128),
  idempotencyShieldTtlMs: Number(process.env.IDEMPOTENCY_SHIELD_TTL_MS || 24 * 60 * 60 * 1000),
  idempotencyShieldProcessingTtlMs: Number(process.env.IDEMPOTENCY_SHIELD_PROCESSING_TTL_MS || 2 * 60 * 1000),
  idempotencyShieldProtectedPrefixes: splitCsv(process.env.IDEMPOTENCY_SHIELD_PROTECTED_PREFIXES || '/api/wallet,/api/wallets,/api/bookings,/api/security/shield,/api/security/runtime/security,/api/security/incidents,/api/security/policy'),
  denylistShieldEnabled: String(process.env.DENYLIST_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  denylistShieldFailOpen: String(process.env.DENYLIST_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  denylistShieldCacheTtlMs: Number(process.env.DENYLIST_SHIELD_CACHE_TTL_MS || 5000),
  denylistDefaultDurationMs: Number(process.env.DENYLIST_DEFAULT_DURATION_MS || 0),
  denylistShieldProtectedPrefixes: splitCsv(process.env.DENYLIST_SHIELD_PROTECTED_PREFIXES || '/api/auth,/api/wallet,/api/wallets,/api/bookings,/api/security,/api/admin'),
  networkIntelPolicyShieldEnabled: String(process.env.NETWORK_INTEL_POLICY_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  networkIntelPolicyShieldFailOpen: String(process.env.NETWORK_INTEL_POLICY_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  networkIntelPolicyCacheTtlMs: Number(process.env.NETWORK_INTEL_POLICY_CACHE_TTL_MS || 3000),
  networkIntelPolicyProtectedPrefixes: splitCsv(process.env.NETWORK_INTEL_POLICY_PROTECTED_PREFIXES || '/api/auth,/api/wallet,/api/wallets,/api/bookings,/api/security,/api/admin'),
  networkIntelDefaultBlockedIpPrefixes: splitCsv(process.env.NETWORK_INTEL_DEFAULT_BLOCKED_IP_PREFIXES || '185.220.,45.95.,198.18.'),
  networkIntelDefaultBlockedAsnHints: splitCsv(process.env.NETWORK_INTEL_DEFAULT_BLOCKED_ASN_HINTS || 'digitalocean,m247,ovh'),
  networkIntelEnforceHostConsistency: String(process.env.NETWORK_INTEL_ENFORCE_HOST_CONSISTENCY || 'true').toLowerCase() === 'true',
  networkIntelBlockHeaderInjection: String(process.env.NETWORK_INTEL_BLOCK_HEADER_INJECTION || 'true').toLowerCase() === 'true',
  networkIntelDefaultDurationMs: Number(process.env.NETWORK_INTEL_DEFAULT_DURATION_MS || 24 * 60 * 60 * 1000),
  networkIntelMaxDurationMs: Number(process.env.NETWORK_INTEL_MAX_DURATION_MS || 7 * 24 * 60 * 60 * 1000),
  routeGuardPolicyShieldEnabled: String(process.env.ROUTE_GUARD_POLICY_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  routeGuardPolicyShieldFailOpen: String(process.env.ROUTE_GUARD_POLICY_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  routeGuardPolicyCacheTtlMs: Number(process.env.ROUTE_GUARD_POLICY_CACHE_TTL_MS || 2000),
  routeGuardPolicyBypassPrefixes: splitCsv(process.env.ROUTE_GUARD_POLICY_BYPASS_PREFIXES || '/health,/api/security/csrf-token,/api/security/shield/route-guard'),
  routeGuardPolicyDefaultDurationMs: Number(process.env.ROUTE_GUARD_POLICY_DEFAULT_DURATION_MS || 60 * 60 * 1000),
  routeGuardPolicyMaxDurationMs: Number(process.env.ROUTE_GUARD_POLICY_MAX_DURATION_MS || 24 * 60 * 60 * 1000),
  adminAuditChainEnabled: String(process.env.ADMIN_AUDIT_CHAIN_ENABLED || 'true').toLowerCase() === 'true',
  adminAuditChainSecret: process.env.ADMIN_AUDIT_CHAIN_SECRET || process.env.JWT_SECRET,
  adminAuditChainTrackReadOps: String(process.env.ADMIN_AUDIT_CHAIN_TRACK_READ_OPS || 'false').toLowerCase() === 'true',
  adminAuditChainTrackPrefixes: splitCsv(process.env.ADMIN_AUDIT_CHAIN_TRACK_PREFIXES || '/api/security,/api/admin'),
  adminAuditChainMaxVerifyLimit: Number(process.env.ADMIN_AUDIT_CHAIN_MAX_VERIFY_LIMIT || 10000),
  attackPatternShieldEnabled: String(process.env.ATTACK_PATTERN_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  attackPatternShieldFailOpen: String(process.env.ATTACK_PATTERN_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  attackPatternShieldFailWindowMs: Number(process.env.ATTACK_PATTERN_SHIELD_FAIL_WINDOW_MS || 15 * 60 * 1000),
  attackPatternShieldHitMax: Number(process.env.ATTACK_PATTERN_SHIELD_HIT_MAX || 4),
  attackPatternShieldQuarantineMs: Number(process.env.ATTACK_PATTERN_SHIELD_QUARANTINE_MS || 60 * 60 * 1000),
  attackPatternShieldQuarantineMaxMs: Number(process.env.ATTACK_PATTERN_SHIELD_QUARANTINE_MAX_MS || 24 * 60 * 60 * 1000),
  attackPatternShieldEscalationFactor: Number(process.env.ATTACK_PATTERN_SHIELD_ESCALATION_FACTOR || 2),
  attackPatternShieldRecordTtlMs: Number(process.env.ATTACK_PATTERN_SHIELD_RECORD_TTL_MS || 7 * 24 * 60 * 60 * 1000),
  attackPatternShieldProtectedPrefixes: splitCsv(process.env.ATTACK_PATTERN_SHIELD_PROTECTED_PREFIXES || '/api/auth,/api/wallet,/api/wallets,/api/bookings,/api/security,/api/admin'),
  globalLockdownShieldEnabled: String(process.env.GLOBAL_LOCKDOWN_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  globalLockdownFailOpen: String(process.env.GLOBAL_LOCKDOWN_FAIL_OPEN || 'false').toLowerCase() === 'true',
  globalLockdownCacheTtlMs: Number(process.env.GLOBAL_LOCKDOWN_CACHE_TTL_MS || 3000),
  globalLockdownLogThrottleMs: Number(process.env.GLOBAL_LOCKDOWN_LOG_THROTTLE_MS || 30000),
  globalLockdownBypassPrefixes: splitCsv(process.env.GLOBAL_LOCKDOWN_BYPASS_PREFIXES || '/health,/api/security/csrf-token,/api/security/lockdown/global'),
  globalLockdownDefaultDurationMs: Number(process.env.GLOBAL_LOCKDOWN_DEFAULT_DURATION_MS || 60 * 60 * 1000),
  globalLockdownMaxDurationMs: Number(process.env.GLOBAL_LOCKDOWN_MAX_DURATION_MS || 24 * 60 * 60 * 1000),
  accessTokenRevocationEnabled: String(process.env.ACCESS_TOKEN_REVOCATION_ENABLED || 'true').toLowerCase() === 'true',
  accessTokenCutoffEnabled: String(process.env.ACCESS_TOKEN_CUTOFF_ENABLED || 'true').toLowerCase() === 'true',
  accessTokenRevocationFailOpen: String(process.env.ACCESS_TOKEN_REVOCATION_FAIL_OPEN || 'false').toLowerCase() === 'true',
  accessTokenRevocationDefaultTtlMs: Number(process.env.ACCESS_TOKEN_REVOCATION_DEFAULT_TTL_MS || 24 * 60 * 60 * 1000),
  accessTokenReplayShieldEnabled: String(process.env.ACCESS_TOKEN_REPLAY_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  accessTokenReplayShieldFailOpen: String(process.env.ACCESS_TOKEN_REPLAY_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  accessTokenReplayMaxDeltaMs: Number(process.env.ACCESS_TOKEN_REPLAY_MAX_DELTA_MS || 10 * 60 * 1000),
  accessTokenReplayRequireFingerprintChange: String(process.env.ACCESS_TOKEN_REPLAY_REQUIRE_FINGERPRINT_CHANGE || 'true').toLowerCase() === 'true',
  accessTokenReplayUserCutoffOnDetect: String(process.env.ACCESS_TOKEN_REPLAY_USER_CUTOFF_ON_DETECT || 'false').toLowerCase() === 'true',
  accessTokenReplayRecordTtlMs: Number(process.env.ACCESS_TOKEN_REPLAY_RECORD_TTL_MS || 24 * 60 * 60 * 1000),
  refreshTokenReplayShieldEnabled: String(process.env.REFRESH_TOKEN_REPLAY_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  refreshTokenReplayShieldFailOpen: String(process.env.REFRESH_TOKEN_REPLAY_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  refreshTokenReplayMaxDeltaMs: Number(process.env.REFRESH_TOKEN_REPLAY_MAX_DELTA_MS || 10 * 60 * 1000),
  refreshTokenReplayRequireFingerprintChange: String(process.env.REFRESH_TOKEN_REPLAY_REQUIRE_FINGERPRINT_CHANGE || 'true').toLowerCase() === 'true',
  refreshTokenReplayIgnoreUnknownCountry: String(process.env.REFRESH_TOKEN_REPLAY_IGNORE_UNKNOWN_COUNTRY || 'true').toLowerCase() === 'true',
  refreshTokenReplayRecordTtlMs: Number(process.env.REFRESH_TOKEN_REPLAY_RECORD_TTL_MS || 30 * 24 * 60 * 60 * 1000),
  refreshTokenReplayAutoCutoffEnabled: String(process.env.REFRESH_TOKEN_REPLAY_AUTO_CUTOFF_ENABLED || 'true').toLowerCase() === 'true',
  refreshTokenReplayAutoClearStoredTokens: String(process.env.REFRESH_TOKEN_REPLAY_AUTO_CLEAR_STORED_TOKENS || 'false').toLowerCase() === 'true',
  refreshTokenReplayAutoBanUser: String(process.env.REFRESH_TOKEN_REPLAY_AUTO_BAN_USER || 'false').toLowerCase() === 'true',
  refreshTokenReplayAutoBanMs: Number(process.env.REFRESH_TOKEN_REPLAY_AUTO_BAN_MS || 2 * 60 * 60 * 1000),
  refreshTokenReplayShieldProtectedPaths: splitCsv(process.env.REFRESH_TOKEN_REPLAY_SHIELD_PROTECTED_PATHS || '/refresh,/refresh-token,/refresh-token-v2,/refresh-secure'),
  geoVelocityShieldEnabled: String(process.env.GEO_VELOCITY_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  geoVelocityShieldFailOpen: String(process.env.GEO_VELOCITY_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  geoVelocityCountryJumpWindowMs: Number(process.env.GEO_VELOCITY_COUNTRY_JUMP_WINDOW_MS || 20 * 60 * 1000),
  geoVelocityRequireFingerprintChange: String(process.env.GEO_VELOCITY_REQUIRE_FINGERPRINT_CHANGE || 'false').toLowerCase() === 'true',
  geoVelocityIgnoreUnknownCountry: String(process.env.GEO_VELOCITY_IGNORE_UNKNOWN_COUNTRY || 'true').toLowerCase() === 'true',
  geoVelocityQuarantineMs: Number(process.env.GEO_VELOCITY_QUARANTINE_MS || 2 * 60 * 60 * 1000),
  geoVelocityQuarantineMaxMs: Number(process.env.GEO_VELOCITY_QUARANTINE_MAX_MS || 24 * 60 * 60 * 1000),
  geoVelocityEscalationFactor: Number(process.env.GEO_VELOCITY_ESCALATION_FACTOR || 2),
  geoVelocityAutoRevokeSessions: String(process.env.GEO_VELOCITY_AUTO_REVOKE_SESSIONS || 'true').toLowerCase() === 'true',
  geoVelocityAutoBanUser: String(process.env.GEO_VELOCITY_AUTO_BAN_USER || 'true').toLowerCase() === 'true',
  sessionContextDriftShieldEnabled: String(process.env.SESSION_CONTEXT_DRIFT_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  sessionContextDriftShieldFailOpen: String(process.env.SESSION_CONTEXT_DRIFT_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  sessionContextDriftWindowMs: Number(process.env.SESSION_CONTEXT_DRIFT_WINDOW_MS || 15 * 60 * 1000),
  sessionContextDriftAnomalyThreshold: Number(process.env.SESSION_CONTEXT_DRIFT_ANOMALY_THRESHOLD || 2),
  sessionContextDriftRequireCountryShift: String(process.env.SESSION_CONTEXT_DRIFT_REQUIRE_COUNTRY_SHIFT || 'false').toLowerCase() === 'true',
  sessionContextDriftQuarantineMs: Number(process.env.SESSION_CONTEXT_DRIFT_QUARANTINE_MS || 2 * 60 * 60 * 1000),
  sessionContextDriftQuarantineMaxMs: Number(process.env.SESSION_CONTEXT_DRIFT_QUARANTINE_MAX_MS || 24 * 60 * 60 * 1000),
  sessionContextDriftEscalationFactor: Number(process.env.SESSION_CONTEXT_DRIFT_ESCALATION_FACTOR || 2),
  sessionContextDriftAutoRevokeSessions: String(process.env.SESSION_CONTEXT_DRIFT_AUTO_REVOKE_SESSIONS || 'true').toLowerCase() === 'true',
  sessionContextDriftAutoBanUser: String(process.env.SESSION_CONTEXT_DRIFT_AUTO_BAN_USER || 'false').toLowerCase() === 'true',
  sessionContextDriftRecordTtlMs: Number(process.env.SESSION_CONTEXT_DRIFT_RECORD_TTL_MS || 30 * 24 * 60 * 60 * 1000),
  sessionFanoutShieldEnabled: String(process.env.SESSION_FANOUT_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  sessionFanoutShieldFailOpen: String(process.env.SESSION_FANOUT_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  sessionFanoutWindowMs: Number(process.env.SESSION_FANOUT_WINDOW_MS || 20 * 60 * 1000),
  sessionFanoutMaxDistinctContexts: Number(process.env.SESSION_FANOUT_MAX_DISTINCT_CONTEXTS || 4),
  sessionFanoutMaxDistinctIps: Number(process.env.SESSION_FANOUT_MAX_DISTINCT_IPS || 3),
  sessionFanoutMaxDistinctCountries: Number(process.env.SESSION_FANOUT_MAX_DISTINCT_COUNTRIES || 2),
  sessionFanoutRequireFingerprint: String(process.env.SESSION_FANOUT_REQUIRE_FINGERPRINT || 'true').toLowerCase() === 'true',
  sessionFanoutQuarantineMs: Number(process.env.SESSION_FANOUT_QUARANTINE_MS || 2 * 60 * 60 * 1000),
  sessionFanoutQuarantineMaxMs: Number(process.env.SESSION_FANOUT_QUARANTINE_MAX_MS || 24 * 60 * 60 * 1000),
  sessionFanoutEscalationFactor: Number(process.env.SESSION_FANOUT_ESCALATION_FACTOR || 2),
  sessionFanoutAutoRevokeSessions: String(process.env.SESSION_FANOUT_AUTO_REVOKE_SESSIONS || 'true').toLowerCase() === 'true',
  sessionFanoutAutoBanUser: String(process.env.SESSION_FANOUT_AUTO_BAN_USER || 'false').toLowerCase() === 'true',
  sessionFanoutRecordTtlMs: Number(process.env.SESSION_FANOUT_RECORD_TTL_MS || 30 * 24 * 60 * 60 * 1000),
  actionVelocityShieldEnabled: String(process.env.ACTION_VELOCITY_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  actionVelocityShieldFailOpen: String(process.env.ACTION_VELOCITY_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  actionVelocityWindowMs: Number(process.env.ACTION_VELOCITY_WINDOW_MS || 10 * 60 * 1000),
  actionVelocityMaxActionCount: Number(process.env.ACTION_VELOCITY_MAX_ACTION_COUNT || 40),
  actionVelocityMaxHighRiskActionCount: Number(process.env.ACTION_VELOCITY_MAX_HIGH_RISK_ACTION_COUNT || 20),
  actionVelocityMaxDistinctRoutes: Number(process.env.ACTION_VELOCITY_MAX_DISTINCT_ROUTES || 12),
  actionVelocityMaxDistinctIps: Number(process.env.ACTION_VELOCITY_MAX_DISTINCT_IPS || 3),
  actionVelocityEnforceMutatingOnly: String(process.env.ACTION_VELOCITY_ENFORCE_MUTATING_ONLY || 'true').toLowerCase() === 'true',
  actionVelocityProtectedPrefixes: splitCsv(process.env.ACTION_VELOCITY_PROTECTED_PREFIXES || '/api/wallet,/api/wallets,/api/bookings,/api/admin,/api/security,/api/users,/api/user'),
  actionVelocityHighRiskPrefixes: splitCsv(process.env.ACTION_VELOCITY_HIGH_RISK_PREFIXES || '/api/wallet,/api/wallets,/api/admin,/api/security'),
  actionVelocityQuarantineMs: Number(process.env.ACTION_VELOCITY_QUARANTINE_MS || 2 * 60 * 60 * 1000),
  actionVelocityQuarantineMaxMs: Number(process.env.ACTION_VELOCITY_QUARANTINE_MAX_MS || 24 * 60 * 60 * 1000),
  actionVelocityEscalationFactor: Number(process.env.ACTION_VELOCITY_ESCALATION_FACTOR || 2),
  actionVelocityAutoRevokeSessions: String(process.env.ACTION_VELOCITY_AUTO_REVOKE_SESSIONS || 'true').toLowerCase() === 'true',
  actionVelocityAutoBanUser: String(process.env.ACTION_VELOCITY_AUTO_BAN_USER || 'false').toLowerCase() === 'true',
  actionVelocityRecordTtlMs: Number(process.env.ACTION_VELOCITY_RECORD_TTL_MS || 30 * 24 * 60 * 60 * 1000),
  privilegeIntegrityShieldEnabled: String(process.env.PRIVILEGE_INTEGRITY_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  privilegeIntegrityShieldFailOpen: String(process.env.PRIVILEGE_INTEGRITY_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  privilegeIntegrityWindowMs: Number(process.env.PRIVILEGE_INTEGRITY_WINDOW_MS || 30 * 60 * 1000),
  privilegeIntegrityAnomalyThreshold: Number(process.env.PRIVILEGE_INTEGRITY_ANOMALY_THRESHOLD || 2),
  privilegeIntegrityStrictRoleMatch: String(process.env.PRIVILEGE_INTEGRITY_STRICT_ROLE_MATCH || 'true').toLowerCase() === 'true',
  privilegeIntegrityStrictAccountTypeMatch: String(process.env.PRIVILEGE_INTEGRITY_STRICT_ACCOUNT_TYPE_MATCH || 'true').toLowerCase() === 'true',
  privilegeIntegrityAllowMissingClaims: String(process.env.PRIVILEGE_INTEGRITY_ALLOW_MISSING_CLAIMS || 'false').toLowerCase() === 'true',
  privilegeIntegrityAdminClaimHardFail: String(process.env.PRIVILEGE_INTEGRITY_ADMIN_CLAIM_HARD_FAIL || 'true').toLowerCase() === 'true',
  privilegeIntegrityQuarantineMs: Number(process.env.PRIVILEGE_INTEGRITY_QUARANTINE_MS || 2 * 60 * 60 * 1000),
  privilegeIntegrityQuarantineMaxMs: Number(process.env.PRIVILEGE_INTEGRITY_QUARANTINE_MAX_MS || 24 * 60 * 60 * 1000),
  privilegeIntegrityEscalationFactor: Number(process.env.PRIVILEGE_INTEGRITY_ESCALATION_FACTOR || 2),
  privilegeIntegrityAutoRevokeSessions: String(process.env.PRIVILEGE_INTEGRITY_AUTO_REVOKE_SESSIONS || 'true').toLowerCase() === 'true',
  privilegeIntegrityAutoBanUser: String(process.env.PRIVILEGE_INTEGRITY_AUTO_BAN_USER || 'true').toLowerCase() === 'true',
  privilegeIntegrityRecordTtlMs: Number(process.env.PRIVILEGE_INTEGRITY_RECORD_TTL_MS || 30 * 24 * 60 * 60 * 1000),
  stepUpAuthShieldEnabled: String(process.env.STEP_UP_AUTH_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  stepUpAuthShieldFailOpen: String(process.env.STEP_UP_AUTH_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  stepUpAuthProtectedPrefixes: splitCsv(process.env.STEP_UP_AUTH_PROTECTED_PREFIXES || '/api/wallet,/api/wallets,/api/bookings,/api/admin,/api/security'),
  stepUpAuthEnforcedMethods: splitCsv(process.env.STEP_UP_AUTH_ENFORCED_METHODS || 'post,put,patch,delete'),
  stepUpAuthMaxTokenAgeMs: Number(process.env.STEP_UP_AUTH_MAX_TOKEN_AGE_MS || 30 * 60 * 1000),
  stepUpAuthRequireIatClaim: String(process.env.STEP_UP_AUTH_REQUIRE_IAT_CLAIM || 'true').toLowerCase() === 'true',
  stepUpAuthAllowAdminBypass: String(process.env.STEP_UP_AUTH_ALLOW_ADMIN_BYPASS || 'false').toLowerCase() === 'true',
  stepUpAuthVerificationHeaders: splitCsv(process.env.STEP_UP_AUTH_VERIFICATION_HEADERS || 'x-otp-verified,x-step-up-auth'),
  stepUpAuthBypassWindowMs: Number(process.env.STEP_UP_AUTH_BYPASS_WINDOW_MS || 20 * 60 * 1000),
  stepUpAuthBypassThreshold: Number(process.env.STEP_UP_AUTH_BYPASS_THRESHOLD || 3),
  stepUpAuthQuarantineMs: Number(process.env.STEP_UP_AUTH_QUARANTINE_MS || 2 * 60 * 60 * 1000),
  stepUpAuthQuarantineMaxMs: Number(process.env.STEP_UP_AUTH_QUARANTINE_MAX_MS || 24 * 60 * 60 * 1000),
  stepUpAuthEscalationFactor: Number(process.env.STEP_UP_AUTH_ESCALATION_FACTOR || 2),
  stepUpAuthAutoRevokeSessions: String(process.env.STEP_UP_AUTH_AUTO_REVOKE_SESSIONS || 'true').toLowerCase() === 'true',
  stepUpAuthAutoBanUser: String(process.env.STEP_UP_AUTH_AUTO_BAN_USER || 'false').toLowerCase() === 'true',
  stepUpAuthRecordTtlMs: Number(process.env.STEP_UP_AUTH_RECORD_TTL_MS || 30 * 24 * 60 * 60 * 1000),
  sessionLineageShieldEnabled: String(process.env.SESSION_LINEAGE_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  sessionLineageShieldFailOpen: String(process.env.SESSION_LINEAGE_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  sessionLineageWindowMs: Number(process.env.SESSION_LINEAGE_WINDOW_MS || 20 * 60 * 1000),
  sessionLineageMaxDistinctSids: Number(process.env.SESSION_LINEAGE_MAX_DISTINCT_SIDS || 4),
  sessionLineageMaxDistinctJtis: Number(process.env.SESSION_LINEAGE_MAX_DISTINCT_JTIS || 120),
  sessionLineageMaxDistinctIps: Number(process.env.SESSION_LINEAGE_MAX_DISTINCT_IPS || 4),
  sessionLineageMaxDistinctCountries: Number(process.env.SESSION_LINEAGE_MAX_DISTINCT_COUNTRIES || 3),
  sessionLineageRequireSidClaim: String(process.env.SESSION_LINEAGE_REQUIRE_SID_CLAIM || 'true').toLowerCase() === 'true',
  sessionLineageMissingSidThreshold: Number(process.env.SESSION_LINEAGE_MISSING_SID_THRESHOLD || 3),
  sessionLineageProtectedPrefixes: splitCsv(process.env.SESSION_LINEAGE_PROTECTED_PREFIXES || '/api/auth,/api/wallet,/api/wallets,/api/bookings,/api/security,/api/admin'),
  sessionLineageQuarantineMs: Number(process.env.SESSION_LINEAGE_QUARANTINE_MS || 2 * 60 * 60 * 1000),
  sessionLineageQuarantineMaxMs: Number(process.env.SESSION_LINEAGE_QUARANTINE_MAX_MS || 24 * 60 * 60 * 1000),
  sessionLineageEscalationFactor: Number(process.env.SESSION_LINEAGE_ESCALATION_FACTOR || 2),
  sessionLineageAutoRevokeSessions: String(process.env.SESSION_LINEAGE_AUTO_REVOKE_SESSIONS || 'true').toLowerCase() === 'true',
  sessionLineageAutoBanUser: String(process.env.SESSION_LINEAGE_AUTO_BAN_USER || 'false').toLowerCase() === 'true',
  sessionLineageRecordTtlMs: Number(process.env.SESSION_LINEAGE_RECORD_TTL_MS || 30 * 24 * 60 * 60 * 1000),
  tokenTemporalIntegrityShieldEnabled: String(process.env.TOKEN_TEMPORAL_INTEGRITY_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  tokenTemporalIntegrityShieldFailOpen: String(process.env.TOKEN_TEMPORAL_INTEGRITY_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  tokenTemporalIntegrityProtectedPrefixes: splitCsv(process.env.TOKEN_TEMPORAL_INTEGRITY_PROTECTED_PREFIXES || '/api/auth,/api/wallet,/api/wallets,/api/bookings,/api/security,/api/admin,/api/users,/api/user'),
  tokenTemporalIntegrityWindowMs: Number(process.env.TOKEN_TEMPORAL_INTEGRITY_WINDOW_MS || 30 * 60 * 1000),
  tokenTemporalIntegrityAnomalyThreshold: Number(process.env.TOKEN_TEMPORAL_INTEGRITY_ANOMALY_THRESHOLD || 2),
  tokenTemporalIntegrityMissingClaimThreshold: Number(process.env.TOKEN_TEMPORAL_INTEGRITY_MISSING_CLAIM_THRESHOLD || 3),
  tokenTemporalIntegrityRequireIatClaim: String(process.env.TOKEN_TEMPORAL_INTEGRITY_REQUIRE_IAT_CLAIM || 'true').toLowerCase() === 'true',
  tokenTemporalIntegrityRequireExpClaim: String(process.env.TOKEN_TEMPORAL_INTEGRITY_REQUIRE_EXP_CLAIM || 'true').toLowerCase() === 'true',
  tokenTemporalIntegrityRequireJtiClaim: String(process.env.TOKEN_TEMPORAL_INTEGRITY_REQUIRE_JTI_CLAIM || 'true').toLowerCase() === 'true',
  tokenTemporalIntegrityHardFailOnMissingClaims: String(process.env.TOKEN_TEMPORAL_INTEGRITY_HARD_FAIL_ON_MISSING_CLAIMS || 'false').toLowerCase() === 'true',
  tokenTemporalIntegrityMaxTokenLifetimeSec: Number(process.env.TOKEN_TEMPORAL_INTEGRITY_MAX_TOKEN_LIFETIME_SEC || 2 * 60 * 60),
  tokenTemporalIntegrityMaxTokenAgeSec: Number(process.env.TOKEN_TEMPORAL_INTEGRITY_MAX_TOKEN_AGE_SEC || 24 * 60 * 60),
  tokenTemporalIntegrityMaxIatFutureSkewSec: Number(process.env.TOKEN_TEMPORAL_INTEGRITY_MAX_IAT_FUTURE_SKEW_SEC || 120),
  tokenTemporalIntegrityMaxNbfFutureSkewSec: Number(process.env.TOKEN_TEMPORAL_INTEGRITY_MAX_NBF_FUTURE_SKEW_SEC || 120),
  tokenTemporalIntegrityQuarantineMs: Number(process.env.TOKEN_TEMPORAL_INTEGRITY_QUARANTINE_MS || 2 * 60 * 60 * 1000),
  tokenTemporalIntegrityQuarantineMaxMs: Number(process.env.TOKEN_TEMPORAL_INTEGRITY_QUARANTINE_MAX_MS || 24 * 60 * 60 * 1000),
  tokenTemporalIntegrityEscalationFactor: Number(process.env.TOKEN_TEMPORAL_INTEGRITY_ESCALATION_FACTOR || 2),
  tokenTemporalIntegrityAutoRevokeSessions: String(process.env.TOKEN_TEMPORAL_INTEGRITY_AUTO_REVOKE_SESSIONS || 'true').toLowerCase() === 'true',
  tokenTemporalIntegrityAutoBanUser: String(process.env.TOKEN_TEMPORAL_INTEGRITY_AUTO_BAN_USER || 'false').toLowerCase() === 'true',
  tokenTemporalIntegrityRecordTtlMs: Number(process.env.TOKEN_TEMPORAL_INTEGRITY_RECORD_TTL_MS || 30 * 24 * 60 * 60 * 1000),
  roleBoundaryShieldEnabled: String(process.env.ROLE_BOUNDARY_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  roleBoundaryShieldFailOpen: String(process.env.ROLE_BOUNDARY_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  roleBoundaryProtectedRules: String(process.env.ROLE_BOUNDARY_PROTECTED_RULES || '/api/admin:admin,/api/security/shield:admin,/api/security/lockdown:admin,/api/security/incidents:admin,/api/security/policy:admin'),
  roleBoundaryExemptPrefixes: splitCsv(process.env.ROLE_BOUNDARY_EXEMPT_PREFIXES || '/api/admin/health'),
  roleBoundaryViolationWindowMs: Number(process.env.ROLE_BOUNDARY_VIOLATION_WINDOW_MS || 30 * 60 * 1000),
  roleBoundaryViolationThreshold: Number(process.env.ROLE_BOUNDARY_VIOLATION_THRESHOLD || 3),
  roleBoundaryResetOnPass: String(process.env.ROLE_BOUNDARY_RESET_ON_PASS || 'true').toLowerCase() === 'true',
  roleBoundaryAllowAdminOverride: String(process.env.ROLE_BOUNDARY_ALLOW_ADMIN_OVERRIDE || 'true').toLowerCase() === 'true',
  roleBoundaryQuarantineMs: Number(process.env.ROLE_BOUNDARY_QUARANTINE_MS || 2 * 60 * 60 * 1000),
  roleBoundaryQuarantineMaxMs: Number(process.env.ROLE_BOUNDARY_QUARANTINE_MAX_MS || 24 * 60 * 60 * 1000),
  roleBoundaryEscalationFactor: Number(process.env.ROLE_BOUNDARY_ESCALATION_FACTOR || 2),
  roleBoundaryAutoRevokeSessions: String(process.env.ROLE_BOUNDARY_AUTO_REVOKE_SESSIONS || 'true').toLowerCase() === 'true',
  roleBoundaryAutoBanUser: String(process.env.ROLE_BOUNDARY_AUTO_BAN_USER || 'false').toLowerCase() === 'true',
  roleBoundaryRecordTtlMs: Number(process.env.ROLE_BOUNDARY_RECORD_TTL_MS || 30 * 24 * 60 * 60 * 1000),
  deviceApprovalBoundaryShieldEnabled: String(process.env.DEVICE_APPROVAL_BOUNDARY_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  deviceApprovalBoundaryShieldFailOpen: String(process.env.DEVICE_APPROVAL_BOUNDARY_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  deviceApprovalBoundaryProtectedPrefixes: splitCsv(process.env.DEVICE_APPROVAL_BOUNDARY_PROTECTED_PREFIXES || '/api/wallet,/api/wallets,/api/bookings,/api/admin,/api/security,/api/users,/api/user'),
  deviceApprovalBoundaryRequireKnownDevice: String(process.env.DEVICE_APPROVAL_BOUNDARY_REQUIRE_KNOWN_DEVICE || 'true').toLowerCase() === 'true',
  deviceApprovalBoundaryAllowMissingFingerprint: String(process.env.DEVICE_APPROVAL_BOUNDARY_ALLOW_MISSING_FINGERPRINT || 'false').toLowerCase() === 'true',
  deviceApprovalBoundaryTreatPendingAsViolation: String(process.env.DEVICE_APPROVAL_BOUNDARY_TREAT_PENDING_AS_VIOLATION || 'true').toLowerCase() === 'true',
  deviceApprovalBoundaryBlockedHardFail: String(process.env.DEVICE_APPROVAL_BOUNDARY_BLOCKED_HARD_FAIL || 'true').toLowerCase() === 'true',
  deviceApprovalBoundaryRejectedHardFail: String(process.env.DEVICE_APPROVAL_BOUNDARY_REJECTED_HARD_FAIL || 'true').toLowerCase() === 'true',
  deviceApprovalBoundaryViolationWindowMs: Number(process.env.DEVICE_APPROVAL_BOUNDARY_VIOLATION_WINDOW_MS || 30 * 60 * 1000),
  deviceApprovalBoundaryViolationThreshold: Number(process.env.DEVICE_APPROVAL_BOUNDARY_VIOLATION_THRESHOLD || 3),
  deviceApprovalBoundaryQuarantineMs: Number(process.env.DEVICE_APPROVAL_BOUNDARY_QUARANTINE_MS || 2 * 60 * 60 * 1000),
  deviceApprovalBoundaryQuarantineMaxMs: Number(process.env.DEVICE_APPROVAL_BOUNDARY_QUARANTINE_MAX_MS || 24 * 60 * 60 * 1000),
  deviceApprovalBoundaryEscalationFactor: Number(process.env.DEVICE_APPROVAL_BOUNDARY_ESCALATION_FACTOR || 2),
  deviceApprovalBoundaryAutoRevokeSessions: String(process.env.DEVICE_APPROVAL_BOUNDARY_AUTO_REVOKE_SESSIONS || 'true').toLowerCase() === 'true',
  deviceApprovalBoundaryAutoBanUser: String(process.env.DEVICE_APPROVAL_BOUNDARY_AUTO_BAN_USER || 'false').toLowerCase() === 'true',
  deviceApprovalBoundaryRecordTtlMs: Number(process.env.DEVICE_APPROVAL_BOUNDARY_RECORD_TTL_MS || 30 * 24 * 60 * 60 * 1000),
  criticalPathCooldownShieldEnabled: String(process.env.CRITICAL_PATH_COOLDOWN_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  criticalPathCooldownShieldFailOpen: String(process.env.CRITICAL_PATH_COOLDOWN_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  criticalPathCooldownProtectedPrefixes: String(process.env.CRITICAL_PATH_COOLDOWN_PROTECTED_PREFIXES || '/api/wallet,/api/wallets,/api/bookings,/api/admin,/api/security,/api/users,/api/user'),
  criticalPathCooldownMethods: String(process.env.CRITICAL_PATH_COOLDOWN_METHODS || 'post,put,patch,delete'),
  criticalPathCooldownMs: Number(process.env.CRITICAL_PATH_COOLDOWN_MS || 2000),
  criticalPathCooldownViolationWindowMs: Number(process.env.CRITICAL_PATH_COOLDOWN_VIOLATION_WINDOW_MS || 15 * 60 * 1000),
  criticalPathCooldownViolationThreshold: Number(process.env.CRITICAL_PATH_COOLDOWN_VIOLATION_THRESHOLD || 4),
  criticalPathCooldownResetWindowOnSafeRequest: String(process.env.CRITICAL_PATH_COOLDOWN_RESET_WINDOW_ON_SAFE_REQUEST || 'false').toLowerCase() === 'true',
  criticalPathCooldownMaxRouteStateEntries: Number(process.env.CRITICAL_PATH_COOLDOWN_MAX_ROUTE_STATE_ENTRIES || 200),
  criticalPathCooldownQuarantineMs: Number(process.env.CRITICAL_PATH_COOLDOWN_QUARANTINE_MS || 2 * 60 * 60 * 1000),
  criticalPathCooldownQuarantineMaxMs: Number(process.env.CRITICAL_PATH_COOLDOWN_QUARANTINE_MAX_MS || 24 * 60 * 60 * 1000),
  criticalPathCooldownEscalationFactor: Number(process.env.CRITICAL_PATH_COOLDOWN_ESCALATION_FACTOR || 2),
  criticalPathCooldownAutoRevokeSessions: String(process.env.CRITICAL_PATH_COOLDOWN_AUTO_REVOKE_SESSIONS || 'true').toLowerCase() === 'true',
  criticalPathCooldownAutoBanUser: String(process.env.CRITICAL_PATH_COOLDOWN_AUTO_BAN_USER || 'false').toLowerCase() === 'true',
  criticalPathCooldownRecordTtlMs: Number(process.env.CRITICAL_PATH_COOLDOWN_RECORD_TTL_MS || 30 * 24 * 60 * 60 * 1000),
  refreshInventoryShieldEnabled: String(process.env.REFRESH_INVENTORY_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  refreshInventoryShieldFailOpen: String(process.env.REFRESH_INVENTORY_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  refreshInventoryProtectedPrefixes: String(process.env.REFRESH_INVENTORY_PROTECTED_PREFIXES || '/api/auth,/api/wallet,/api/wallets,/api/bookings,/api/security,/api/admin,/api/users,/api/user'),
  refreshInventoryWindowMs: Number(process.env.REFRESH_INVENTORY_WINDOW_MS || 30 * 60 * 1000),
  refreshInventoryMaxActiveTokens: Number(process.env.REFRESH_INVENTORY_MAX_ACTIVE_TOKENS || 8),
  refreshInventoryMaxMissingSessionTokens: Number(process.env.REFRESH_INVENTORY_MAX_MISSING_SESSION_TOKENS || 2),
  refreshInventoryMaxDuplicateSessionTokens: Number(process.env.REFRESH_INVENTORY_MAX_DUPLICATE_SESSION_TOKENS || 3),
  refreshInventoryRequireSessionId: String(process.env.REFRESH_INVENTORY_REQUIRE_SESSION_ID || 'false').toLowerCase() === 'true',
  refreshInventoryViolationThreshold: Number(process.env.REFRESH_INVENTORY_VIOLATION_THRESHOLD || 2),
  refreshInventoryQuarantineMs: Number(process.env.REFRESH_INVENTORY_QUARANTINE_MS || 2 * 60 * 60 * 1000),
  refreshInventoryQuarantineMaxMs: Number(process.env.REFRESH_INVENTORY_QUARANTINE_MAX_MS || 24 * 60 * 60 * 1000),
  refreshInventoryEscalationFactor: Number(process.env.REFRESH_INVENTORY_ESCALATION_FACTOR || 2),
  refreshInventoryAutoRevokeSessions: String(process.env.REFRESH_INVENTORY_AUTO_REVOKE_SESSIONS || 'true').toLowerCase() === 'true',
  refreshInventoryAutoBanUser: String(process.env.REFRESH_INVENTORY_AUTO_BAN_USER || 'false').toLowerCase() === 'true',
  refreshInventoryRecordTtlMs: Number(process.env.REFRESH_INVENTORY_RECORD_TTL_MS || 30 * 24 * 60 * 60 * 1000),
  requestFreshnessShieldEnabled: String(process.env.REQUEST_FRESHNESS_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  requestFreshnessShieldFailOpen: String(process.env.REQUEST_FRESHNESS_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  requestFreshnessProtectedPrefixes: String(process.env.REQUEST_FRESHNESS_PROTECTED_PREFIXES || '/api/wallet,/api/wallets,/api/bookings,/api/admin,/api/security,/api/users,/api/user'),
  requestFreshnessMethods: String(process.env.REQUEST_FRESHNESS_METHODS || 'post,put,patch,delete'),
  requestFreshnessRequireRequestId: String(process.env.REQUEST_FRESHNESS_REQUIRE_REQUEST_ID || 'true').toLowerCase() === 'true',
  requestFreshnessRequestIdMinLength: Number(process.env.REQUEST_FRESHNESS_REQUEST_ID_MIN_LENGTH || 12),
  requestFreshnessRequestIdMaxLength: Number(process.env.REQUEST_FRESHNESS_REQUEST_ID_MAX_LENGTH || 160),
  requestFreshnessRequireTimestamp: String(process.env.REQUEST_FRESHNESS_REQUIRE_TIMESTAMP || 'true').toLowerCase() === 'true',
  requestFreshnessMaxSkewMs: Number(process.env.REQUEST_FRESHNESS_MAX_SKEW_MS || 5 * 60 * 1000),
  requestFreshnessReplayWindowMs: Number(process.env.REQUEST_FRESHNESS_REPLAY_WINDOW_MS || 10 * 60 * 1000),
  requestFreshnessWindowMs: Number(process.env.REQUEST_FRESHNESS_WINDOW_MS || 20 * 60 * 1000),
  requestFreshnessViolationThreshold: Number(process.env.REQUEST_FRESHNESS_VIOLATION_THRESHOLD || 3),
  requestFreshnessMaxRememberedRequestIds: Number(process.env.REQUEST_FRESHNESS_MAX_REMEMBERED_REQUEST_IDS || 300),
  requestFreshnessQuarantineMs: Number(process.env.REQUEST_FRESHNESS_QUARANTINE_MS || 2 * 60 * 60 * 1000),
  requestFreshnessQuarantineMaxMs: Number(process.env.REQUEST_FRESHNESS_QUARANTINE_MAX_MS || 24 * 60 * 60 * 1000),
  requestFreshnessEscalationFactor: Number(process.env.REQUEST_FRESHNESS_ESCALATION_FACTOR || 2),
  requestFreshnessAutoRevokeSessions: String(process.env.REQUEST_FRESHNESS_AUTO_REVOKE_SESSIONS || 'true').toLowerCase() === 'true',
  requestFreshnessAutoBanUser: String(process.env.REQUEST_FRESHNESS_AUTO_BAN_USER || 'false').toLowerCase() === 'true',
  requestFreshnessRecordTtlMs: Number(process.env.REQUEST_FRESHNESS_RECORD_TTL_MS || 30 * 24 * 60 * 60 * 1000),
  tokenClaimBoundaryShieldEnabled: String(process.env.TOKEN_CLAIM_BOUNDARY_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  tokenClaimBoundaryShieldFailOpen: String(process.env.TOKEN_CLAIM_BOUNDARY_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  tokenClaimBoundaryProtectedPrefixes: String(process.env.TOKEN_CLAIM_BOUNDARY_PROTECTED_PREFIXES || '/api/admin,/api/security,/api/wallet,/api/wallets,/api/bookings'),
  tokenClaimBoundaryMethods: String(process.env.TOKEN_CLAIM_BOUNDARY_METHODS || 'post,put,patch,delete'),
  tokenClaimBoundaryRequireIssuer: String(process.env.TOKEN_CLAIM_BOUNDARY_REQUIRE_ISSUER || 'true').toLowerCase() === 'true',
  tokenClaimBoundaryRequiredIssuer: String(process.env.TOKEN_CLAIM_BOUNDARY_REQUIRED_ISSUER || process.env.JWT_ISSUER || ''),
  tokenClaimBoundaryRequireAudience: String(process.env.TOKEN_CLAIM_BOUNDARY_REQUIRE_AUDIENCE || 'true').toLowerCase() === 'true',
  tokenClaimBoundaryRequiredAudience: String(process.env.TOKEN_CLAIM_BOUNDARY_REQUIRED_AUDIENCE || process.env.JWT_AUDIENCE || ''),
  tokenClaimBoundaryRequireScopeRules: String(process.env.TOKEN_CLAIM_BOUNDARY_REQUIRE_SCOPE_RULES || 'true').toLowerCase() === 'true',
  tokenClaimBoundaryScopeRules: String(process.env.TOKEN_CLAIM_BOUNDARY_SCOPE_RULES || '/api/admin:post|put|patch|delete:admin.full|admin.write|role:admin;/api/security:post|put|patch|delete:admin.full|security.write|role:admin;/api/wallet:post|put|patch|delete:wallet.write|admin.full|role:customer|role:driver|role:admin;/api/wallets:post|put|patch|delete:wallet.write|admin.full|role:customer|role:driver|role:admin;/api/bookings:post|put|patch|delete:booking.write|admin.full|role:customer|role:driver|role:admin'),
  tokenClaimBoundaryScopeClaimKeys: String(process.env.TOKEN_CLAIM_BOUNDARY_SCOPE_CLAIM_KEYS || 'scope,scp,permissions'),
  tokenClaimBoundaryAllowRoleScopeFallback: String(process.env.TOKEN_CLAIM_BOUNDARY_ALLOW_ROLE_SCOPE_FALLBACK || 'true').toLowerCase() === 'true',
  tokenClaimBoundaryViolationWindowMs: Number(process.env.TOKEN_CLAIM_BOUNDARY_VIOLATION_WINDOW_MS || 20 * 60 * 1000),
  tokenClaimBoundaryViolationThreshold: Number(process.env.TOKEN_CLAIM_BOUNDARY_VIOLATION_THRESHOLD || 3),
  tokenClaimBoundaryMissingClaimThreshold: Number(process.env.TOKEN_CLAIM_BOUNDARY_MISSING_CLAIM_THRESHOLD || 4),
  tokenClaimBoundaryResetWindowOnPass: String(process.env.TOKEN_CLAIM_BOUNDARY_RESET_WINDOW_ON_PASS || 'true').toLowerCase() === 'true',
  tokenClaimBoundaryQuarantineMs: Number(process.env.TOKEN_CLAIM_BOUNDARY_QUARANTINE_MS || 2 * 60 * 60 * 1000),
  tokenClaimBoundaryQuarantineMaxMs: Number(process.env.TOKEN_CLAIM_BOUNDARY_QUARANTINE_MAX_MS || 24 * 60 * 60 * 1000),
  tokenClaimBoundaryEscalationFactor: Number(process.env.TOKEN_CLAIM_BOUNDARY_ESCALATION_FACTOR || 2),
  tokenClaimBoundaryAutoRevokeSessions: String(process.env.TOKEN_CLAIM_BOUNDARY_AUTO_REVOKE_SESSIONS || 'true').toLowerCase() === 'true',
  tokenClaimBoundaryAutoBanUser: String(process.env.TOKEN_CLAIM_BOUNDARY_AUTO_BAN_USER || 'false').toLowerCase() === 'true',
  tokenClaimBoundaryRecordTtlMs: Number(process.env.TOKEN_CLAIM_BOUNDARY_RECORD_TTL_MS || 30 * 24 * 60 * 60 * 1000),
  tokenHeaderIntegrityShieldEnabled: String(process.env.TOKEN_HEADER_INTEGRITY_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  tokenHeaderIntegrityShieldFailOpen: String(process.env.TOKEN_HEADER_INTEGRITY_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  tokenHeaderIntegrityProtectedPrefixes: String(process.env.TOKEN_HEADER_INTEGRITY_PROTECTED_PREFIXES || '/api/admin,/api/security,/api/wallet,/api/wallets,/api/bookings'),
  tokenHeaderIntegrityMethods: String(process.env.TOKEN_HEADER_INTEGRITY_METHODS || 'post,put,patch,delete'),
  tokenHeaderIntegrityMaxHeaderBytes: Number(process.env.TOKEN_HEADER_INTEGRITY_MAX_HEADER_BYTES || 2048),
  tokenHeaderIntegrityAllowedAlgorithms: String(process.env.TOKEN_HEADER_INTEGRITY_ALLOWED_ALGORITHMS || 'HS256'),
  tokenHeaderIntegrityRejectNoneAlgorithm: String(process.env.TOKEN_HEADER_INTEGRITY_REJECT_NONE_ALGORITHM || 'true').toLowerCase() === 'true',
  tokenHeaderIntegrityRequireTyp: String(process.env.TOKEN_HEADER_INTEGRITY_REQUIRE_TYP || 'true').toLowerCase() === 'true',
  tokenHeaderIntegrityAllowedTypValues: String(process.env.TOKEN_HEADER_INTEGRITY_ALLOWED_TYP_VALUES || 'jwt'),
  tokenHeaderIntegrityRequireKid: String(process.env.TOKEN_HEADER_INTEGRITY_REQUIRE_KID || 'false').toLowerCase() === 'true',
  tokenHeaderIntegrityAllowedKids: splitCsv(process.env.TOKEN_HEADER_INTEGRITY_ALLOWED_KIDS),
  tokenHeaderIntegrityDisallowExternalKeyRefs: String(process.env.TOKEN_HEADER_INTEGRITY_DISALLOW_EXTERNAL_KEY_REFS || 'true').toLowerCase() === 'true',
  tokenHeaderIntegrityDisallowCriticalHeader: String(process.env.TOKEN_HEADER_INTEGRITY_DISALLOW_CRITICAL_HEADER || 'true').toLowerCase() === 'true',
  tokenHeaderIntegrityDisallowNestedJwtHeader: String(process.env.TOKEN_HEADER_INTEGRITY_DISALLOW_NESTED_JWT_HEADER || 'true').toLowerCase() === 'true',
  tokenHeaderIntegrityViolationWindowMs: Number(process.env.TOKEN_HEADER_INTEGRITY_VIOLATION_WINDOW_MS || 20 * 60 * 1000),
  tokenHeaderIntegrityViolationThreshold: Number(process.env.TOKEN_HEADER_INTEGRITY_VIOLATION_THRESHOLD || 3),
  tokenHeaderIntegrityMissingFieldThreshold: Number(process.env.TOKEN_HEADER_INTEGRITY_MISSING_FIELD_THRESHOLD || 4),
  tokenHeaderIntegrityResetWindowOnPass: String(process.env.TOKEN_HEADER_INTEGRITY_RESET_WINDOW_ON_PASS || 'true').toLowerCase() === 'true',
  tokenHeaderIntegrityQuarantineMs: Number(process.env.TOKEN_HEADER_INTEGRITY_QUARANTINE_MS || 2 * 60 * 60 * 1000),
  tokenHeaderIntegrityQuarantineMaxMs: Number(process.env.TOKEN_HEADER_INTEGRITY_QUARANTINE_MAX_MS || 24 * 60 * 60 * 1000),
  tokenHeaderIntegrityEscalationFactor: Number(process.env.TOKEN_HEADER_INTEGRITY_ESCALATION_FACTOR || 2),
  tokenHeaderIntegrityAutoRevokeSessions: String(process.env.TOKEN_HEADER_INTEGRITY_AUTO_REVOKE_SESSIONS || 'true').toLowerCase() === 'true',
  tokenHeaderIntegrityAutoBanUser: String(process.env.TOKEN_HEADER_INTEGRITY_AUTO_BAN_USER || 'false').toLowerCase() === 'true',
  tokenHeaderIntegrityRecordTtlMs: Number(process.env.TOKEN_HEADER_INTEGRITY_RECORD_TTL_MS || 30 * 24 * 60 * 60 * 1000),
  tokenPayloadHygieneShieldEnabled: String(process.env.TOKEN_PAYLOAD_HYGIENE_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  tokenPayloadHygieneShieldFailOpen: String(process.env.TOKEN_PAYLOAD_HYGIENE_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  tokenPayloadHygieneProtectedPrefixes: String(process.env.TOKEN_PAYLOAD_HYGIENE_PROTECTED_PREFIXES || '/api/admin,/api/security,/api/wallet,/api/wallets,/api/bookings'),
  tokenPayloadHygieneMethods: String(process.env.TOKEN_PAYLOAD_HYGIENE_METHODS || 'post,put,patch,delete'),
  tokenPayloadHygieneMaxPayloadBytes: Number(process.env.TOKEN_PAYLOAD_HYGIENE_MAX_PAYLOAD_BYTES || 4096),
  tokenPayloadHygieneMaxClaimCount: Number(process.env.TOKEN_PAYLOAD_HYGIENE_MAX_CLAIM_COUNT || 30),
  tokenPayloadHygieneMaxClaimStringLength: Number(process.env.TOKEN_PAYLOAD_HYGIENE_MAX_CLAIM_STRING_LENGTH || 512),
  tokenPayloadHygieneMaxScopeCount: Number(process.env.TOKEN_PAYLOAD_HYGIENE_MAX_SCOPE_COUNT || 25),
  tokenPayloadHygieneMaxScopeValueLength: Number(process.env.TOKEN_PAYLOAD_HYGIENE_MAX_SCOPE_VALUE_LENGTH || 120),
  tokenPayloadHygieneRequireSidClaim: String(process.env.TOKEN_PAYLOAD_HYGIENE_REQUIRE_SID_CLAIM || 'true').toLowerCase() === 'true',
  tokenPayloadHygieneRequireJtiClaim: String(process.env.TOKEN_PAYLOAD_HYGIENE_REQUIRE_JTI_CLAIM || 'true').toLowerCase() === 'true',
  tokenPayloadHygieneRequireRoleClaim: String(process.env.TOKEN_PAYLOAD_HYGIENE_REQUIRE_ROLE_CLAIM || 'true').toLowerCase() === 'true',
  tokenPayloadHygieneRequireAccountTypeClaim: String(process.env.TOKEN_PAYLOAD_HYGIENE_REQUIRE_ACCOUNT_TYPE_CLAIM || 'true').toLowerCase() === 'true',
  tokenPayloadHygieneAllowUnknownClaims: String(process.env.TOKEN_PAYLOAD_HYGIENE_ALLOW_UNKNOWN_CLAIMS || 'false').toLowerCase() === 'true',
  tokenPayloadHygieneAllowedClaims: String(process.env.TOKEN_PAYLOAD_HYGIENE_ALLOWED_CLAIMS || 'sub,role,accountType,sid,jti,iat,exp,nbf,iss,aud,scope,scp,permissions,type'),
  tokenPayloadHygieneDenyPrivilegeLikeCustomClaims: String(process.env.TOKEN_PAYLOAD_HYGIENE_DENY_PRIVILEGE_LIKE_CUSTOM_CLAIMS || 'true').toLowerCase() === 'true',
  tokenPayloadHygieneViolationWindowMs: Number(process.env.TOKEN_PAYLOAD_HYGIENE_VIOLATION_WINDOW_MS || 20 * 60 * 1000),
  tokenPayloadHygieneViolationThreshold: Number(process.env.TOKEN_PAYLOAD_HYGIENE_VIOLATION_THRESHOLD || 3),
  tokenPayloadHygieneMissingClaimThreshold: Number(process.env.TOKEN_PAYLOAD_HYGIENE_MISSING_CLAIM_THRESHOLD || 4),
  tokenPayloadHygieneResetWindowOnPass: String(process.env.TOKEN_PAYLOAD_HYGIENE_RESET_WINDOW_ON_PASS || 'true').toLowerCase() === 'true',
  tokenPayloadHygieneQuarantineMs: Number(process.env.TOKEN_PAYLOAD_HYGIENE_QUARANTINE_MS || 2 * 60 * 60 * 1000),
  tokenPayloadHygieneQuarantineMaxMs: Number(process.env.TOKEN_PAYLOAD_HYGIENE_QUARANTINE_MAX_MS || 24 * 60 * 60 * 1000),
  tokenPayloadHygieneEscalationFactor: Number(process.env.TOKEN_PAYLOAD_HYGIENE_ESCALATION_FACTOR || 2),
  tokenPayloadHygieneAutoRevokeSessions: String(process.env.TOKEN_PAYLOAD_HYGIENE_AUTO_REVOKE_SESSIONS || 'true').toLowerCase() === 'true',
  tokenPayloadHygieneAutoBanUser: String(process.env.TOKEN_PAYLOAD_HYGIENE_AUTO_BAN_USER || 'false').toLowerCase() === 'true',
  tokenPayloadHygieneRecordTtlMs: Number(process.env.TOKEN_PAYLOAD_HYGIENE_RECORD_TTL_MS || 30 * 24 * 60 * 60 * 1000),
  tokenIdentifierHardeningShieldEnabled: String(process.env.TOKEN_IDENTIFIER_HARDENING_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  tokenIdentifierHardeningShieldFailOpen: String(process.env.TOKEN_IDENTIFIER_HARDENING_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  tokenIdentifierHardeningProtectedPrefixes: String(process.env.TOKEN_IDENTIFIER_HARDENING_PROTECTED_PREFIXES || '/api/admin,/api/security,/api/wallet,/api/wallets,/api/bookings'),
  tokenIdentifierHardeningMethods: String(process.env.TOKEN_IDENTIFIER_HARDENING_METHODS || 'post,put,patch,delete'),
  tokenIdentifierHardeningRequireSidClaim: String(process.env.TOKEN_IDENTIFIER_HARDENING_REQUIRE_SID_CLAIM || 'true').toLowerCase() === 'true',
  tokenIdentifierHardeningRequireJtiClaim: String(process.env.TOKEN_IDENTIFIER_HARDENING_REQUIRE_JTI_CLAIM || 'true').toLowerCase() === 'true',
  tokenIdentifierHardeningSidMinLength: Number(process.env.TOKEN_IDENTIFIER_HARDENING_SID_MIN_LENGTH || 20),
  tokenIdentifierHardeningSidMaxLength: Number(process.env.TOKEN_IDENTIFIER_HARDENING_SID_MAX_LENGTH || 120),
  tokenIdentifierHardeningJtiMinLength: Number(process.env.TOKEN_IDENTIFIER_HARDENING_JTI_MIN_LENGTH || 20),
  tokenIdentifierHardeningJtiMaxLength: Number(process.env.TOKEN_IDENTIFIER_HARDENING_JTI_MAX_LENGTH || 120),
  tokenIdentifierHardeningAllowedPattern: String(process.env.TOKEN_IDENTIFIER_HARDENING_ALLOWED_PATTERN || '^[A-Za-z0-9._:-]+$'),
  tokenIdentifierHardeningMinUniqueCharRatio: Number(process.env.TOKEN_IDENTIFIER_HARDENING_MIN_UNIQUE_CHAR_RATIO || 0.35),
  tokenIdentifierHardeningDisallowSidEqualsJti: String(process.env.TOKEN_IDENTIFIER_HARDENING_DISALLOW_SID_EQUALS_JTI || 'true').toLowerCase() === 'true',
  tokenIdentifierHardeningDisallowSequentialPattern: String(process.env.TOKEN_IDENTIFIER_HARDENING_DISALLOW_SEQUENTIAL_PATTERN || 'true').toLowerCase() === 'true',
  tokenIdentifierHardeningSequentialRunMinLength: Number(process.env.TOKEN_IDENTIFIER_HARDENING_SEQUENTIAL_RUN_MIN_LENGTH || 5),
  tokenIdentifierHardeningDisallowRepeatedPattern: String(process.env.TOKEN_IDENTIFIER_HARDENING_DISALLOW_REPEATED_PATTERN || 'true').toLowerCase() === 'true',
  tokenIdentifierHardeningDisallowWeakDenylist: String(process.env.TOKEN_IDENTIFIER_HARDENING_DISALLOW_WEAK_DENYLIST || 'true').toLowerCase() === 'true',
  tokenIdentifierHardeningWeakIdentifierDenylist: String(process.env.TOKEN_IDENTIFIER_HARDENING_WEAK_IDENTIFIER_DENYLIST || '12345,123456,123456789,abcdef,qwerty,password,token,session,test,admin,root'),
  tokenIdentifierHardeningViolationWindowMs: Number(process.env.TOKEN_IDENTIFIER_HARDENING_VIOLATION_WINDOW_MS || 20 * 60 * 1000),
  tokenIdentifierHardeningViolationThreshold: Number(process.env.TOKEN_IDENTIFIER_HARDENING_VIOLATION_THRESHOLD || 3),
  tokenIdentifierHardeningMissingClaimThreshold: Number(process.env.TOKEN_IDENTIFIER_HARDENING_MISSING_CLAIM_THRESHOLD || 4),
  tokenIdentifierHardeningResetWindowOnPass: String(process.env.TOKEN_IDENTIFIER_HARDENING_RESET_WINDOW_ON_PASS || 'true').toLowerCase() === 'true',
  tokenIdentifierHardeningQuarantineMs: Number(process.env.TOKEN_IDENTIFIER_HARDENING_QUARANTINE_MS || 2 * 60 * 60 * 1000),
  tokenIdentifierHardeningQuarantineMaxMs: Number(process.env.TOKEN_IDENTIFIER_HARDENING_QUARANTINE_MAX_MS || 24 * 60 * 60 * 1000),
  tokenIdentifierHardeningEscalationFactor: Number(process.env.TOKEN_IDENTIFIER_HARDENING_ESCALATION_FACTOR || 2),
  tokenIdentifierHardeningAutoRevokeSessions: String(process.env.TOKEN_IDENTIFIER_HARDENING_AUTO_REVOKE_SESSIONS || 'true').toLowerCase() === 'true',
  tokenIdentifierHardeningAutoBanUser: String(process.env.TOKEN_IDENTIFIER_HARDENING_AUTO_BAN_USER || 'false').toLowerCase() === 'true',
  tokenIdentifierHardeningRecordTtlMs: Number(process.env.TOKEN_IDENTIFIER_HARDENING_RECORD_TTL_MS || 30 * 24 * 60 * 60 * 1000),
  tokenTypeSeparationShieldEnabled: String(process.env.TOKEN_TYPE_SEPARATION_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  tokenTypeSeparationShieldFailOpen: String(process.env.TOKEN_TYPE_SEPARATION_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  tokenTypeSeparationProtectedPrefixes: String(process.env.TOKEN_TYPE_SEPARATION_PROTECTED_PREFIXES || '/api/admin,/api/security,/api/wallet,/api/wallets,/api/bookings,/api/users,/api/user'),
  tokenTypeSeparationMethods: String(process.env.TOKEN_TYPE_SEPARATION_METHODS || 'post,put,patch,delete'),
  tokenTypeSeparationEnforceOnAllMethods: String(process.env.TOKEN_TYPE_SEPARATION_ENFORCE_ON_ALL_METHODS || 'false').toLowerCase() === 'true',
  tokenTypeSeparationRequireTokenTypeClaim: String(process.env.TOKEN_TYPE_SEPARATION_REQUIRE_TOKEN_TYPE_CLAIM || 'false').toLowerCase() === 'true',
  tokenTypeSeparationRequireAccessTokenType: String(process.env.TOKEN_TYPE_SEPARATION_REQUIRE_ACCESS_TOKEN_TYPE || 'false').toLowerCase() === 'true',
  tokenTypeSeparationForbiddenTokenTypes: String(process.env.TOKEN_TYPE_SEPARATION_FORBIDDEN_TOKEN_TYPES || 'refresh,refresh_token'),
  tokenTypeSeparationAllowedTokenTypes: String(process.env.TOKEN_TYPE_SEPARATION_ALLOWED_TOKEN_TYPES || 'access,access_token,bearer'),
  tokenTypeSeparationRefreshScopeHints: String(process.env.TOKEN_TYPE_SEPARATION_REFRESH_SCOPE_HINTS || 'token.refresh,refresh.rotate,session.refresh'),
  tokenTypeSeparationRefreshClaimKeys: String(process.env.TOKEN_TYPE_SEPARATION_REFRESH_CLAIM_KEYS || 'type,tokenUse,token_use,kind'),
  tokenTypeSeparationViolationWindowMs: Number(process.env.TOKEN_TYPE_SEPARATION_VIOLATION_WINDOW_MS || 20 * 60 * 1000),
  tokenTypeSeparationViolationThreshold: Number(process.env.TOKEN_TYPE_SEPARATION_VIOLATION_THRESHOLD || 3),
  tokenTypeSeparationMissingClaimThreshold: Number(process.env.TOKEN_TYPE_SEPARATION_MISSING_CLAIM_THRESHOLD || 4),
  tokenTypeSeparationResetWindowOnPass: String(process.env.TOKEN_TYPE_SEPARATION_RESET_WINDOW_ON_PASS || 'true').toLowerCase() === 'true',
  tokenTypeSeparationQuarantineMs: Number(process.env.TOKEN_TYPE_SEPARATION_QUARANTINE_MS || 2 * 60 * 60 * 1000),
  tokenTypeSeparationQuarantineMaxMs: Number(process.env.TOKEN_TYPE_SEPARATION_QUARANTINE_MAX_MS || 24 * 60 * 60 * 1000),
  tokenTypeSeparationEscalationFactor: Number(process.env.TOKEN_TYPE_SEPARATION_ESCALATION_FACTOR || 2),
  tokenTypeSeparationAutoRevokeSessions: String(process.env.TOKEN_TYPE_SEPARATION_AUTO_REVOKE_SESSIONS || 'true').toLowerCase() === 'true',
  tokenTypeSeparationAutoBanUser: String(process.env.TOKEN_TYPE_SEPARATION_AUTO_BAN_USER || 'false').toLowerCase() === 'true',
  tokenTypeSeparationRecordTtlMs: Number(process.env.TOKEN_TYPE_SEPARATION_RECORD_TTL_MS || 30 * 24 * 60 * 60 * 1000),
  tokenSessionAnchorShieldEnabled: String(process.env.TOKEN_SESSION_ANCHOR_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  tokenSessionAnchorShieldFailOpen: String(process.env.TOKEN_SESSION_ANCHOR_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  tokenSessionAnchorProtectedPrefixes: String(process.env.TOKEN_SESSION_ANCHOR_PROTECTED_PREFIXES || '/api/admin,/api/security,/api/wallet,/api/wallets,/api/bookings,/api/users,/api/user,/api/auth'),
  tokenSessionAnchorMethods: String(process.env.TOKEN_SESSION_ANCHOR_METHODS || 'post,put,patch,delete'),
  tokenSessionAnchorEnforceOnAllMethods: String(process.env.TOKEN_SESSION_ANCHOR_ENFORCE_ON_ALL_METHODS || 'false').toLowerCase() === 'true',
  tokenSessionAnchorRequireSidClaim: String(process.env.TOKEN_SESSION_ANCHOR_REQUIRE_SID_CLAIM || 'true').toLowerCase() === 'true',
  tokenSessionAnchorRequireAnchorMatch: String(process.env.TOKEN_SESSION_ANCHOR_REQUIRE_ANCHOR_MATCH || 'true').toLowerCase() === 'true',
  tokenSessionAnchorMinRefreshTokenRemainingMs: Number(process.env.TOKEN_SESSION_ANCHOR_MIN_REFRESH_TOKEN_REMAINING_MS || 60000),
  tokenSessionAnchorMaxAgeMs: Number(process.env.TOKEN_SESSION_ANCHOR_MAX_AGE_MS || 0),
  tokenSessionAnchorMaxSessionSidDuplicates: Number(process.env.TOKEN_SESSION_ANCHOR_MAX_SESSION_SID_DUPLICATES || 4),
  tokenSessionAnchorRequireFingerprintMatch: String(process.env.TOKEN_SESSION_ANCHOR_REQUIRE_FINGERPRINT_MATCH || 'true').toLowerCase() === 'true',
  tokenSessionAnchorAllowMissingFingerprint: String(process.env.TOKEN_SESSION_ANCHOR_ALLOW_MISSING_FINGERPRINT || 'false').toLowerCase() === 'true',
  tokenSessionAnchorRequireUserAgentMatch: String(process.env.TOKEN_SESSION_ANCHOR_REQUIRE_USER_AGENT_MATCH || 'false').toLowerCase() === 'true',
  tokenSessionAnchorAllowMissingUserAgent: String(process.env.TOKEN_SESSION_ANCHOR_ALLOW_MISSING_USER_AGENT || 'true').toLowerCase() === 'true',
  tokenSessionAnchorViolationWindowMs: Number(process.env.TOKEN_SESSION_ANCHOR_VIOLATION_WINDOW_MS || 20 * 60 * 1000),
  tokenSessionAnchorViolationThreshold: Number(process.env.TOKEN_SESSION_ANCHOR_VIOLATION_THRESHOLD || 3),
  tokenSessionAnchorMissingClaimThreshold: Number(process.env.TOKEN_SESSION_ANCHOR_MISSING_CLAIM_THRESHOLD || 4),
  tokenSessionAnchorResetWindowOnPass: String(process.env.TOKEN_SESSION_ANCHOR_RESET_WINDOW_ON_PASS || 'true').toLowerCase() === 'true',
  tokenSessionAnchorQuarantineMs: Number(process.env.TOKEN_SESSION_ANCHOR_QUARANTINE_MS || 2 * 60 * 60 * 1000),
  tokenSessionAnchorQuarantineMaxMs: Number(process.env.TOKEN_SESSION_ANCHOR_QUARANTINE_MAX_MS || 24 * 60 * 60 * 1000),
  tokenSessionAnchorEscalationFactor: Number(process.env.TOKEN_SESSION_ANCHOR_ESCALATION_FACTOR || 2),
  tokenSessionAnchorAutoRevokeSessions: String(process.env.TOKEN_SESSION_ANCHOR_AUTO_REVOKE_SESSIONS || 'true').toLowerCase() === 'true',
  tokenSessionAnchorAutoBanUser: String(process.env.TOKEN_SESSION_ANCHOR_AUTO_BAN_USER || 'false').toLowerCase() === 'true',
  tokenSessionAnchorRecordTtlMs: Number(process.env.TOKEN_SESSION_ANCHOR_RECORD_TTL_MS || 30 * 24 * 60 * 60 * 1000),
  csrfCookieName: String(process.env.CSRF_COOKIE_NAME || 'gir_csrf_token'),
  csrfTokenTtlMinutes: Number(process.env.CSRF_TOKEN_TTL_MINUTES || 720),

  securityGatewayEnabled: String(process.env.SECURITY_GATEWAY_ENABLED || 'true').toLowerCase() === 'true',
  securityGatewayMaxUrlLength: Number(process.env.SECURITY_GATEWAY_MAX_URL_LENGTH || 2048),
  securityGatewayMaxHeaderCount: Number(process.env.SECURITY_GATEWAY_MAX_HEADER_COUNT || 120),
  securityGatewayMaxBodyDepth: Number(process.env.SECURITY_GATEWAY_MAX_BODY_DEPTH || 10),
  securityGatewayMaxBodyKeys: Number(process.env.SECURITY_GATEWAY_MAX_BODY_KEYS || 800),
  securityGatewayMaxArrayLength: Number(process.env.SECURITY_GATEWAY_MAX_ARRAY_LENGTH || 5000),
  securityGatewayMaxStringLength: Number(process.env.SECURITY_GATEWAY_MAX_STRING_LENGTH || 10000),
  securityGatewayRequireKnownContentType: String(process.env.SECURITY_GATEWAY_REQUIRE_KNOWN_CONTENT_TYPE || 'true').toLowerCase() === 'true',
  securityGatewayPrincipalFailWindowMs: Number(process.env.SECURITY_GATEWAY_PRINCIPAL_FAIL_WINDOW_MS || 10 * 60 * 1000),
  securityGatewayPrincipalFailMax: Number(process.env.SECURITY_GATEWAY_PRINCIPAL_FAIL_MAX || 15),
  securityGatewayPrincipalBlockMs: Number(process.env.SECURITY_GATEWAY_PRINCIPAL_BLOCK_MS || 30 * 60 * 1000),
  securityGatewayPrincipalBlockMaxMs: Number(process.env.SECURITY_GATEWAY_PRINCIPAL_BLOCK_MAX_MS || 24 * 60 * 60 * 1000),
  securityGatewayPrincipalEscalationFactor: Number(process.env.SECURITY_GATEWAY_PRINCIPAL_ESCALATION_FACTOR || 2),

  recaptchaVerifyServerSide: String(process.env.RECAPTCHA_VERIFY_SERVER_SIDE || 'true').toLowerCase() === 'true',
  recaptchaFailOpen: String(process.env.RECAPTCHA_FAIL_OPEN || 'false').toLowerCase() === 'true',
  recaptchaMinScore: Number(process.env.RECAPTCHA_MIN_SCORE || 0.5),

  authAbuseShieldEnabled: String(process.env.AUTH_ABUSE_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  authAbusePersistentEnabled: String(process.env.AUTH_ABUSE_PERSISTENT_ENABLED || 'true').toLowerCase() === 'true',
  authAbusePersistentFailOpen: String(process.env.AUTH_ABUSE_PERSISTENT_FAIL_OPEN || 'true').toLowerCase() === 'true',
  authAbusePersistentRetentionMs: Number(process.env.AUTH_ABUSE_PERSISTENT_RETENTION_MS || 14 * 24 * 60 * 60 * 1000),
  authAbuseFailWindowMs: Number(process.env.AUTH_ABUSE_FAIL_WINDOW_MS || 15 * 60 * 1000),
  authAbusePrincipalFailMax: Number(process.env.AUTH_ABUSE_PRINCIPAL_FAIL_MAX || 8),
  authAbuseIpFailMax: Number(process.env.AUTH_ABUSE_IP_FAIL_MAX || 25),
  authAbuseBlockMs: Number(process.env.AUTH_ABUSE_BLOCK_MS || 30 * 60 * 1000),
  authAbuseBlockMaxMs: Number(process.env.AUTH_ABUSE_BLOCK_MAX_MS || 24 * 60 * 60 * 1000),
  authAbuseEscalationFactor: Number(process.env.AUTH_ABUSE_ESCALATION_FACTOR || 2),
  authAbuseResetOnSuccess: String(process.env.AUTH_ABUSE_RESET_ON_SUCCESS || 'true').toLowerCase() === 'true',
  authAbuseTrackPaths: splitCsv(process.env.AUTH_ABUSE_TRACK_PATHS),
  credentialStuffingShieldEnabled: String(process.env.CREDENTIAL_STUFFING_SHIELD_ENABLED || 'true').toLowerCase() === 'true',
  credentialStuffingShieldFailOpen: String(process.env.CREDENTIAL_STUFFING_SHIELD_FAIL_OPEN || 'false').toLowerCase() === 'true',
  credentialStuffingFailWindowMs: Number(process.env.CREDENTIAL_STUFFING_FAIL_WINDOW_MS || 10 * 60 * 1000),
  credentialStuffingFailureMax: Number(process.env.CREDENTIAL_STUFFING_FAILURE_MAX || 20),
  credentialStuffingUniquePrincipalMax: Number(process.env.CREDENTIAL_STUFFING_UNIQUE_PRINCIPAL_MAX || 8),
  credentialStuffingQuarantineMs: Number(process.env.CREDENTIAL_STUFFING_QUARANTINE_MS || 30 * 60 * 1000),
  credentialStuffingQuarantineMaxMs: Number(process.env.CREDENTIAL_STUFFING_QUARANTINE_MAX_MS || 24 * 60 * 60 * 1000),
  credentialStuffingEscalationFactor: Number(process.env.CREDENTIAL_STUFFING_ESCALATION_FACTOR || 2),
  credentialStuffingRecordTtlMs: Number(process.env.CREDENTIAL_STUFFING_RECORD_TTL_MS || 14 * 24 * 60 * 60 * 1000),
  credentialStuffingTrackPaths: splitCsv(process.env.CREDENTIAL_STUFFING_TRACK_PATHS || '/api/auth/login,/api/auth/admin/login,/api/auth/register,/api/auth/forgot-password/request,/api/auth/forgot-password/confirm'),
  recaptchaVerifyTimeoutMs: Number(process.env.RECAPTCHA_VERIFY_TIMEOUT_MS || 3500)
};
